//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class acc_accgroups
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public acc_accgroups()
        {
            this.acc_accprivilege = new HashSet<acc_accprivilege>();
            this.visitor_visitor_acc_groups = new HashSet<visitor_visitor_acc_groups>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public string create_user { get; set; }
        public Nullable<System.DateTime> change_time { get; set; }
        public string change_user { get; set; }
        public short status { get; set; }
        public int group_no { get; set; }
        public string group_name { get; set; }
        public int verify_mode { get; set; }
        public Nullable<int> timezone1 { get; set; }
        public Nullable<int> timezone2 { get; set; }
        public Nullable<int> timezone3 { get; set; }
        public short is_include_holiday { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
        public int area_id { get; set; }
    
        public virtual personnel_area personnel_area { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<acc_accprivilege> acc_accprivilege { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<visitor_visitor_acc_groups> visitor_visitor_acc_groups { get; set; }
    }
}
