//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class acc_acctimezone
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public acc_acctimezone()
        {
            this.acc_accholiday = new HashSet<acc_accholiday>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public string create_user { get; set; }
        public Nullable<System.DateTime> change_time { get; set; }
        public string change_user { get; set; }
        public short status { get; set; }
        public int timezone_no { get; set; }
        public string timezone_name { get; set; }
        public System.DateTime sun_start { get; set; }
        public System.DateTime sun_end { get; set; }
        public Nullable<short> sun_on { get; set; }
        public System.DateTime mon_start { get; set; }
        public System.DateTime mon_end { get; set; }
        public Nullable<short> mon_on { get; set; }
        public System.DateTime tue_start { get; set; }
        public System.DateTime tue_end { get; set; }
        public Nullable<short> tue_on { get; set; }
        public System.DateTime wed_start { get; set; }
        public System.DateTime wed_end { get; set; }
        public Nullable<short> wed_on { get; set; }
        public System.DateTime thu_start { get; set; }
        public System.DateTime thu_end { get; set; }
        public Nullable<short> thu_on { get; set; }
        public System.DateTime fri_start { get; set; }
        public System.DateTime fri_end { get; set; }
        public Nullable<short> fri_on { get; set; }
        public System.DateTime sat_start { get; set; }
        public System.DateTime sat_end { get; set; }
        public Nullable<short> sat_on { get; set; }
        public string remark { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
        public int area_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<acc_accholiday> acc_accholiday { get; set; }
        public virtual personnel_area personnel_area { get; set; }
    }
}
