//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class acc_accholiday
    {
        public int id { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public string create_user { get; set; }
        public Nullable<System.DateTime> change_time { get; set; }
        public string change_user { get; set; }
        public short status { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
        public int area_id { get; set; }
        public int holiday_id { get; set; }
        public int timezone_id { get; set; }
    
        public virtual personnel_area personnel_area { get; set; }
        public virtual att_holiday att_holiday { get; set; }
        public virtual acc_acctimezone acc_acctimezone { get; set; }
    }
}
