//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class acc_accterminal
    {
        public int id { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public string create_user { get; set; }
        public Nullable<System.DateTime> change_time { get; set; }
        public string change_user { get; set; }
        public short status { get; set; }
        public string door_name { get; set; }
        public int door_lock_delay { get; set; }
        public int door_sensor_delay { get; set; }
        public short door_sensor_type { get; set; }
        public int door_alarm_delay { get; set; }
        public short retry_times { get; set; }
        public short valid_holiday { get; set; }
        public int nc_time_period { get; set; }
        public int no_time_period { get; set; }
        public short speaker_alarm { get; set; }
        public short duress_fun_on { get; set; }
        public short alarm_1_1 { get; set; }
        public short alarm_1_n { get; set; }
        public short alarm_password { get; set; }
        public int duress_alarm_delay { get; set; }
        public short anti_passback_mode { get; set; }
        public short anti_door_direction { get; set; }
        public short verify_mode_485 { get; set; }
        public Nullable<System.DateTime> push_time { get; set; }
        public int terminal_id { get; set; }
    
        public virtual iclock_terminal iclock_terminal { get; set; }
    }
}
