//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class acc_acccombination
    {
        public int id { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public string create_user { get; set; }
        public Nullable<System.DateTime> change_time { get; set; }
        public string change_user { get; set; }
        public short status { get; set; }
        public int combination_no { get; set; }
        public string combination_name { get; set; }
        public Nullable<int> group1 { get; set; }
        public Nullable<int> group2 { get; set; }
        public Nullable<int> group3 { get; set; }
        public Nullable<int> group4 { get; set; }
        public Nullable<int> group5 { get; set; }
        public string remark { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
        public int area_id { get; set; }
    
        public virtual personnel_area personnel_area { get; set; }
    }
}
