//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class acc_accprivilege
    {
        public int id { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public string create_user { get; set; }
        public Nullable<System.DateTime> change_time { get; set; }
        public string change_user { get; set; }
        public short status { get; set; }
        public short is_group_timezone { get; set; }
        public Nullable<int> timezone1 { get; set; }
        public Nullable<int> timezone2 { get; set; }
        public Nullable<int> timezone3 { get; set; }
        public short is_group_verifycode { get; set; }
        public Nullable<int> verify_mode { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
        public int area_id { get; set; }
        public int employee_id { get; set; }
        public int group_id { get; set; }
    
        public virtual acc_accgroups acc_accgroups { get; set; }
        public virtual personnel_area personnel_area { get; set; }
        public virtual personnel_employee personnel_employee { get; set; }
    }
}
