//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class accounts_adminbiodata
    {
        public int id { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public string create_user { get; set; }
        public Nullable<System.DateTime> change_time { get; set; }
        public string change_user { get; set; }
        public short status { get; set; }
        public string bio_tmp { get; set; }
        public Nullable<int> bio_no { get; set; }
        public Nullable<int> bio_index { get; set; }
        public int bio_type { get; set; }
        public string major_ver { get; set; }
        public string minor_ver { get; set; }
        public Nullable<int> bio_format { get; set; }
        public bool valid { get; set; }
        public bool duress { get; set; }
        public int admin_id { get; set; }
    
        public virtual auth_user auth_user { get; set; }
    }
}
