//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class accounts_usernotification
    {
        public int id { get; set; }
        public Nullable<int> category { get; set; }
        public Nullable<int> @event { get; set; }
        public string content { get; set; }
        public System.DateTime send_time { get; set; }
        public Nullable<System.DateTime> read_time { get; set; }
        public short status { get; set; }
        public int user_id { get; set; }
    
        public virtual auth_user auth_user { get; set; }
    }
}
