//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class att_breaktime
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public att_breaktime()
        {
            this.att_timeinterval_break_time = new HashSet<att_timeinterval_break_time>();
        }
    
        public int id { get; set; }
        public string alias { get; set; }
        public System.DateTime period_start { get; set; }
        public int duration { get; set; }
        public int end_margin { get; set; }
        public short func_key { get; set; }
        public short available_interval_type { get; set; }
        public int available_interval { get; set; }
        public short multiple_punch { get; set; }
        public short calc_type { get; set; }
        public Nullable<int> minimum_duration { get; set; }
        public short early_in { get; set; }
        public short late_in { get; set; }
        public bool profit_rule { get; set; }
        public int min_early_in { get; set; }
        public bool loss_rule { get; set; }
        public int min_late_in { get; set; }
        public Nullable<int> loss_code_id { get; set; }
        public Nullable<int> profit_code_id { get; set; }
        public short with_salary { get; set; }
    
        public virtual att_paycode att_paycode { get; set; }
        public virtual att_paycode att_paycode1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<att_timeinterval_break_time> att_timeinterval_break_time { get; set; }
    }
}
