//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class att_attreportsetting
    {
        public int id { get; set; }
        public bool filter_by_hire_date { get; set; }
        public short resign_emp { get; set; }
        public short short_date { get; set; }
        public short short_time { get; set; }
        public bool auto_calculate { get; set; }
        public Nullable<System.DateTime> calculate_time { get; set; }
    }
}
