//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class att_attshift
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public att_attshift()
        {
            this.att_attschedule = new HashSet<att_attschedule>();
            this.att_departmentschedule = new HashSet<att_departmentschedule>();
            this.att_groupschedule = new HashSet<att_groupschedule>();
            this.att_payloadattcode = new HashSet<att_payloadattcode>();
            this.att_payloadpaycode = new HashSet<att_payloadpaycode>();
            this.att_shiftdetail = new HashSet<att_shiftdetail>();
        }
    
        public int id { get; set; }
        public string alias { get; set; }
        public short cycle_unit { get; set; }
        public int shift_cycle { get; set; }
        public bool work_weekend { get; set; }
        public short weekend_type { get; set; }
        public bool work_day_off { get; set; }
        public short day_off_type { get; set; }
        public short auto_shift { get; set; }
        public bool enable_ot_rule { get; set; }
        public short frequency { get; set; }
        public string ot_rule { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<att_attschedule> att_attschedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<att_departmentschedule> att_departmentschedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<att_groupschedule> att_groupschedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<att_payloadattcode> att_payloadattcode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<att_payloadpaycode> att_payloadpaycode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<att_shiftdetail> att_shiftdetail { get; set; }
    }
}
