//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class att_leavegroupdetail
    {
        public int id { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public string create_user { get; set; }
        public Nullable<System.DateTime> change_time { get; set; }
        public string change_user { get; set; }
        public short status { get; set; }
        public int leave_type { get; set; }
        public int allow_leave_day { get; set; }
        public double min_leave_day { get; set; }
        public short deduct_holiday_day { get; set; }
        public Nullable<int> leave_entitlement { get; set; }
        public int leave_interval { get; set; }
        public Nullable<int> leave_distribution_time { get; set; }
        public string start_day { get; set; }
        public short set_hire_day { get; set; }
        public short allow_exceed_limit { get; set; }
        public short allow_balance { get; set; }
        public Nullable<int> max_balance { get; set; }
        public string entitlement_detail { get; set; }
        public int leave_group_id { get; set; }
        public Nullable<int> pay_code_id { get; set; }
    
        public virtual att_leavegroup att_leavegroup { get; set; }
        public virtual att_paycode att_paycode { get; set; }
    }
}
