//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class att_holiday
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public att_holiday()
        {
            this.acc_accholiday = new HashSet<acc_accholiday>();
        }
    
        public int id { get; set; }
        public string alias { get; set; }
        public System.DateTime start_date { get; set; }
        public short duration_day { get; set; }
        public bool enable_ot_rule { get; set; }
        public string ot_rule { get; set; }
        public string color_setting { get; set; }
        public Nullable<int> att_group_id { get; set; }
        public Nullable<int> department_id { get; set; }
        public System.DateTime end_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<acc_accholiday> acc_accholiday { get; set; }
        public virtual att_attgroup att_attgroup { get; set; }
        public virtual personnel_department personnel_department { get; set; }
    }
}
