//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class att_attemployee
    {
        public int id { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public string create_user { get; set; }
        public Nullable<System.DateTime> change_time { get; set; }
        public string change_user { get; set; }
        public short status { get; set; }
        public bool enable_attendance { get; set; }
        public bool enable_schedule { get; set; }
        public bool enable_overtime { get; set; }
        public bool enable_holiday { get; set; }
        public int emp_id { get; set; }
        public Nullable<int> group_id { get; set; }
        public bool enable_compensatory { get; set; }
        public string ip_address { get; set; }
    
        public virtual personnel_employee personnel_employee { get; set; }
        public virtual att_attgroup att_attgroup { get; set; }
    }
}
