//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class att_payloadbase
    {
        public string uuid { get; set; }
        public Nullable<System.DateTime> att_date { get; set; }
        public Nullable<short> weekday { get; set; }
        public Nullable<System.DateTime> check_in { get; set; }
        public Nullable<System.DateTime> check_out { get; set; }
        public Nullable<int> duration { get; set; }
        public Nullable<int> duty_duration { get; set; }
        public double work_day { get; set; }
        public Nullable<System.DateTime> clock_in { get; set; }
        public Nullable<System.DateTime> clock_out { get; set; }
        public Nullable<int> total_time { get; set; }
        public Nullable<int> duty_worked { get; set; }
        public Nullable<int> actual_worked { get; set; }
        public Nullable<int> unscheduled { get; set; }
        public Nullable<int> remaining { get; set; }
        public Nullable<int> total_worked { get; set; }
        public Nullable<int> late { get; set; }
        public Nullable<int> early_leave { get; set; }
        public Nullable<int> @short { get; set; }
        public Nullable<int> absent { get; set; }
        public Nullable<int> leave { get; set; }
        public string exception { get; set; }
        public short day_off { get; set; }
        public string break_time_id { get; set; }
        public int emp_id { get; set; }
        public string overtime_id { get; set; }
        public Nullable<int> timetable_id { get; set; }
    
        public virtual personnel_employee personnel_employee { get; set; }
        public virtual att_timeinterval att_timeinterval { get; set; }
    }
}
