//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class att_paycode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public att_paycode()
        {
            this.att_attpolicy = new HashSet<att_attpolicy>();
            this.att_breaktime = new HashSet<att_breaktime>();
            this.att_breaktime1 = new HashSet<att_breaktime>();
            this.att_departmentpolicy = new HashSet<att_departmentpolicy>();
            this.att_grouppolicy = new HashSet<att_grouppolicy>();
            this.att_leave = new HashSet<att_leave>();
            this.att_leavegroupdetail = new HashSet<att_leavegroupdetail>();
            this.att_leaveyearbalance = new HashSet<att_leaveyearbalance>();
            this.att_overtime = new HashSet<att_overtime>();
            this.att_overtimepolicy = new HashSet<att_overtimepolicy>();
            this.att_overtimepolicy1 = new HashSet<att_overtimepolicy>();
            this.att_payloadparing = new HashSet<att_payloadparing>();
            this.att_payloadpaycode = new HashSet<att_payloadpaycode>();
            this.att_timeinterval = new HashSet<att_timeinterval>();
            this.att_training = new HashSet<att_training>();
            this.payroll_exceptionformula = new HashSet<payroll_exceptionformula>();
            this.payroll_leaveformula = new HashSet<payroll_leaveformula>();
            this.payroll_overtimeformula = new HashSet<payroll_overtimeformula>();
            this.payroll_payrollpayloadpaycode = new HashSet<payroll_payrollpayloadpaycode>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public string create_user { get; set; }
        public Nullable<System.DateTime> change_time { get; set; }
        public string change_user { get; set; }
        public short status { get; set; }
        public string code { get; set; }
        public string name { get; set; }
        public short code_type { get; set; }
        public Nullable<short> tag { get; set; }
        public Nullable<short> fixed_code { get; set; }
        public bool is_work { get; set; }
        public decimal fixed_hours { get; set; }
        public bool is_paid { get; set; }
        public bool is_benefit { get; set; }
        public short round_off { get; set; }
        public decimal min_val { get; set; }
        public short display_format { get; set; }
        public string symbol { get; set; }
        public short display_order { get; set; }
        public string desc { get; set; }
        public bool is_display { get; set; }
        public bool is_default { get; set; }
        public string color_setting { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<att_attpolicy> att_attpolicy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<att_breaktime> att_breaktime { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<att_breaktime> att_breaktime1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<att_departmentpolicy> att_departmentpolicy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<att_grouppolicy> att_grouppolicy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<att_leave> att_leave { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<att_leavegroupdetail> att_leavegroupdetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<att_leaveyearbalance> att_leaveyearbalance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<att_overtime> att_overtime { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<att_overtimepolicy> att_overtimepolicy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<att_overtimepolicy> att_overtimepolicy1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<att_payloadparing> att_payloadparing { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<att_payloadpaycode> att_payloadpaycode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<att_timeinterval> att_timeinterval { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<att_training> att_training { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<payroll_exceptionformula> payroll_exceptionformula { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<payroll_leaveformula> payroll_leaveformula { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<payroll_overtimeformula> payroll_overtimeformula { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<payroll_payrollpayloadpaycode> payroll_payrollpayloadpaycode { get; set; }
    }
}
