//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class att_timeinterval
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public att_timeinterval()
        {
            this.att_changeschedule = new HashSet<att_changeschedule>();
            this.att_payloadbase = new HashSet<att_payloadbase>();
            this.att_payloadtimecard = new HashSet<att_payloadtimecard>();
            this.att_shiftdetail = new HashSet<att_shiftdetail>();
            this.att_timeinterval_break_time = new HashSet<att_timeinterval_break_time>();
        }
    
        public int id { get; set; }
        public string alias { get; set; }
        public short use_mode { get; set; }
        public System.DateTime in_time { get; set; }
        public int in_ahead_margin { get; set; }
        public int in_above_margin { get; set; }
        public int out_ahead_margin { get; set; }
        public int out_above_margin { get; set; }
        public int duration { get; set; }
        public short in_required { get; set; }
        public short out_required { get; set; }
        public int allow_late { get; set; }
        public int allow_leave_early { get; set; }
        public double work_day { get; set; }
        public short early_in { get; set; }
        public int min_early_in { get; set; }
        public bool count_early_in_interval { get; set; }
        public short late_out { get; set; }
        public int min_late_out { get; set; }
        public bool count_late_out_interval { get; set; }
        public short overtime_lv { get; set; }
        public short overtime_lv1 { get; set; }
        public short overtime_lv2 { get; set; }
        public short overtime_lv3 { get; set; }
        public short multiple_punch { get; set; }
        public short available_interval_type { get; set; }
        public int available_interval { get; set; }
        public int work_time_duration { get; set; }
        public short func_key { get; set; }
        public short work_type { get; set; }
        public System.DateTime day_change { get; set; }
        public bool enable_early_in { get; set; }
        public bool enable_late_out { get; set; }
        public bool enable_overtime { get; set; }
        public string ot_rule { get; set; }
        public string color_setting { get; set; }
        public bool enable_max_ot_limit { get; set; }
        public int max_ot_limit { get; set; }
        public short overtime_policy { get; set; }
        public Nullable<int> ot_pay_code_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<att_changeschedule> att_changeschedule { get; set; }
        public virtual att_paycode att_paycode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<att_payloadbase> att_payloadbase { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<att_payloadtimecard> att_payloadtimecard { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<att_shiftdetail> att_shiftdetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<att_timeinterval_break_time> att_timeinterval_break_time { get; set; }
    }
}
