//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class att_payloadtimecard
    {
        public string id { get; set; }
        public System.DateTime att_date { get; set; }
        public int week { get; set; }
        public int weekday { get; set; }
        public short date_type { get; set; }
        public string time_table_alias { get; set; }
        public System.DateTime check_in { get; set; }
        public System.DateTime check_out { get; set; }
        public decimal work_day { get; set; }
        public Nullable<System.DateTime> clock_in { get; set; }
        public Nullable<System.DateTime> clock_out { get; set; }
        public Nullable<System.DateTime> break_out { get; set; }
        public Nullable<System.DateTime> break_in { get; set; }
        public bool lock_down { get; set; }
        public short present { get; set; }
        public int emp_id { get; set; }
        public Nullable<int> time_table_id { get; set; }
        public short full_attendance { get; set; }
        public Nullable<int> in_trans_id { get; set; }
        public Nullable<int> out_trans_id { get; set; }
        public string payload { get; set; }
    
        public virtual personnel_employee personnel_employee { get; set; }
        public virtual iclock_transaction iclock_transaction { get; set; }
        public virtual iclock_transaction iclock_transaction1 { get; set; }
        public virtual att_timeinterval att_timeinterval { get; set; }
    }
}
