//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class att_payloadovertime
    {
        public string uuid { get; set; }
        public Nullable<int> normal_wt { get; set; }
        public Nullable<int> normal_ot { get; set; }
        public Nullable<int> weekend_ot { get; set; }
        public Nullable<int> holiday_ot { get; set; }
        public Nullable<int> ot_lv1 { get; set; }
        public Nullable<int> ot_lv2 { get; set; }
        public Nullable<int> ot_lv3 { get; set; }
        public Nullable<int> total_ot { get; set; }
    }
}
