//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class att_payloadeffectpunch
    {
        public string id { get; set; }
        public System.DateTime att_date { get; set; }
        public System.DateTime punch_datetime { get; set; }
        public System.DateTime punch_date { get; set; }
        public System.DateTime punch_time { get; set; }
        public short week { get; set; }
        public short weekday { get; set; }
        public string work_code { get; set; }
        public string punch_state { get; set; }
        public string adjust_state { get; set; }
        public int emp_id { get; set; }
        public string time_card_id { get; set; }
        public int trans_id { get; set; }
    
        public virtual personnel_employee personnel_employee { get; set; }
        public virtual iclock_transaction iclock_transaction { get; set; }
    }
}
