//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class att_payloadmulpunchset
    {
        public int id { get; set; }
        public System.DateTime att_date { get; set; }
        public Nullable<short> weekday { get; set; }
        public short data_index { get; set; }
        public Nullable<System.DateTime> clock_in { get; set; }
        public Nullable<int> in_id { get; set; }
        public Nullable<System.DateTime> clock_out { get; set; }
        public Nullable<int> out_id { get; set; }
        public Nullable<int> total_time { get; set; }
        public Nullable<int> worked_time { get; set; }
        public short data_type { get; set; }
        public int emp_id { get; set; }
        public Nullable<int> timetable_id { get; set; }
    
        public virtual personnel_employee personnel_employee { get; set; }
    }
}
