//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class att_payloadpaycode
    {
        public string id { get; set; }
        public System.DateTime att_date { get; set; }
        public int week { get; set; }
        public int weekday { get; set; }
        public string pay_code_alias { get; set; }
        public string pay_code_symbol { get; set; }
        public int duration { get; set; }
        public decimal workday { get; set; }
        public decimal hours { get; set; }
        public decimal minutes { get; set; }
        public short is_exception { get; set; }
        public bool is_weekly { get; set; }
        public int year { get; set; }
        public int emp_id { get; set; }
        public int pay_code_id { get; set; }
        public Nullable<int> shift_id { get; set; }
        public string time_card_id { get; set; }
    
        public virtual att_attshift att_attshift { get; set; }
        public virtual att_paycode att_paycode { get; set; }
        public virtual personnel_employee personnel_employee { get; set; }
    }
}
