//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class att_leave
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public att_leave()
        {
            this.att_payloadexception = new HashSet<att_payloadexception>();
        }
    
        public int workflowinstance_ptr_id { get; set; }
        public System.DateTime start_time { get; set; }
        public System.DateTime end_time { get; set; }
        public string apply_reason { get; set; }
        public System.DateTime apply_time { get; set; }
        public string attachment { get; set; }
        public double leave_day { get; set; }
        public Nullable<int> pay_code_id { get; set; }
    
        public virtual att_paycode att_paycode { get; set; }
        public virtual workflow_workflowinstance workflow_workflowinstance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<att_payloadexception> att_payloadexception { get; set; }
    }
}
