//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class att_payloadexception
    {
        public string uuid { get; set; }
        public System.DateTime start_time { get; set; }
        public System.DateTime end_time { get; set; }
        public Nullable<int> duration { get; set; }
        public Nullable<double> days { get; set; }
        public short data_type { get; set; }
        public string description { get; set; }
        public Nullable<int> item_id { get; set; }
        public string skd_id { get; set; }
    
        public virtual att_leave att_leave { get; set; }
    }
}
