//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class att_timeinterval_break_time
    {
        public int id { get; set; }
        public int timeinterval_id { get; set; }
        public int breaktime_id { get; set; }
    
        public virtual att_breaktime att_breaktime { get; set; }
        public virtual att_timeinterval att_timeinterval { get; set; }
    }
}
