//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Att_adj
    {
        public int Id { get; set; }
        public int emp_ID { get; set; }
        [Display(Name = "For Which date")]
        public System.DateTime which_date { get; set; }
        [Display(Name = "Late In")]
        public Nullable<System.TimeSpan> late_in { get; set; }
        [Display(Name = "Early out")]
        public Nullable<System.TimeSpan> early_out { get; set; }
        public string reason { get; set; }
        public string ap1 { get; set; }
        public string ap2 { get; set; }
        public System.DateTime date_added { get; set; }
        public System.DateTime date_modified { get; set; }
    
        public virtual master_file master_file { get; set; }
    }
}
