//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class att_reporttemplate
    {
        public int id { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public string create_user { get; set; }
        public Nullable<System.DateTime> change_time { get; set; }
        public string change_user { get; set; }
        public short status { get; set; }
        public string report { get; set; }
        public string template_name { get; set; }
        public string template_value { get; set; }
        public bool is_share { get; set; }
        public bool is_auto_export { get; set; }
        public bool fixed_date_period { get; set; }
        public string language { get; set; }
        public Nullable<int> builder_id { get; set; }
        public Nullable<int> employee_id { get; set; }
    
        public virtual auth_user auth_user { get; set; }
        public virtual personnel_employee personnel_employee { get; set; }
    }
}
