//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class att_payloadparing
    {
        public string id { get; set; }
        public long stamp { get; set; }
        public System.DateTime att_date { get; set; }
        public short week { get; set; }
        public short weekday { get; set; }
        public short data_type { get; set; }
        public Nullable<System.DateTime> clock_in { get; set; }
        public Nullable<System.DateTime> in_date { get; set; }
        public Nullable<System.DateTime> in_time { get; set; }
        public Nullable<System.DateTime> clock_out { get; set; }
        public Nullable<System.DateTime> out_date { get; set; }
        public Nullable<System.DateTime> out_time { get; set; }
        public int duration { get; set; }
        public int worked_duration { get; set; }
        public int data_index { get; set; }
        public decimal workday { get; set; }
        public int emp_id { get; set; }
        public Nullable<int> in_trans_id { get; set; }
        public Nullable<int> out_trans_id { get; set; }
        public Nullable<int> pay_code_id { get; set; }
        public string time_card_id { get; set; }
    
        public virtual att_paycode att_paycode { get; set; }
        public virtual personnel_employee personnel_employee { get; set; }
        public virtual iclock_transaction iclock_transaction { get; set; }
        public virtual iclock_transaction iclock_transaction1 { get; set; }
    }
}
