//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class att_attcode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public att_attcode()
        {
            this.att_payloadattcode = new HashSet<att_payloadattcode>();
        }
    
        public int id { get; set; }
        public string code { get; set; }
        public string alias { get; set; }
        public short display_format { get; set; }
        public string symbol { get; set; }
        public short round_off { get; set; }
        public decimal min_val { get; set; }
        public bool symbol_only { get; set; }
        public short order { get; set; }
        public string color_setting { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<att_payloadattcode> att_payloadattcode { get; set; }
    }
}
