//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATTENDANCE_ADJUSTMENT
    {
        public int Id { get; set; }
        public Nullable<int> Employee_id { get; set; }
        public Nullable<System.DateTime> date_prepared { get; set; }
        public Nullable<System.DateTime> DJ_date { get; set; }
        public Nullable<System.TimeSpan> late_in { get; set; }
        public Nullable<System.TimeSpan> early_out { get; set; }
        public string reason { get; set; }
    
        public virtual master_file master_file { get; set; }
    }
}
