//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class auth_user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public auth_user()
        {
            this.accounts_adminbiodata = new HashSet<accounts_adminbiodata>();
            this.accounts_usernotification = new HashSet<accounts_usernotification>();
            this.att_reporttemplate = new HashSet<att_reporttemplate>();
            this.auth_user_auth_area = new HashSet<auth_user_auth_area>();
            this.auth_user_auth_dept = new HashSet<auth_user_auth_dept>();
            this.auth_user_groups = new HashSet<auth_user_groups>();
            this.auth_user_profile = new HashSet<auth_user_profile>();
            this.auth_user_user_permissions = new HashSet<auth_user_user_permissions>();
            this.authtoken_token = new HashSet<authtoken_token>();
            this.base_adminlog = new HashSet<base_adminlog>();
            this.base_bookmark = new HashSet<base_bookmark>();
            this.django_admin_log = new HashSet<django_admin_log>();
            this.guardian_userobjectpermission = new HashSet<guardian_userobjectpermission>();
            this.mobile_announcement = new HashSet<mobile_announcement>();
            this.mobile_appnotification = new HashSet<mobile_appnotification>();
            this.rest_framework_tracking_apirequestlog = new HashSet<rest_framework_tracking_apirequestlog>();
        }
    
        public int id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string emp_pin { get; set; }
        public string email { get; set; }
        public string tele_phone { get; set; }
        public Nullable<int> auth_time_dept { get; set; }
        public Nullable<int> login_id { get; set; }
        public Nullable<int> login_type { get; set; }
        public Nullable<int> login_count { get; set; }
        public bool is_staff { get; set; }
        public bool is_active { get; set; }
        public bool is_superuser { get; set; }
        public bool is_public { get; set; }
        public bool can_manage_all_dept { get; set; }
        public Nullable<int> del_flag { get; set; }
        public System.DateTime date_joined { get; set; }
        public Nullable<System.DateTime> last_login { get; set; }
        public string session_key { get; set; }
        public string login_ip { get; set; }
        public string photo { get; set; }
        public Nullable<int> assign_company { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<accounts_adminbiodata> accounts_adminbiodata { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<accounts_usernotification> accounts_usernotification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<att_reporttemplate> att_reporttemplate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<auth_user_auth_area> auth_user_auth_area { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<auth_user_auth_dept> auth_user_auth_dept { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<auth_user_groups> auth_user_groups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<auth_user_profile> auth_user_profile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<auth_user_user_permissions> auth_user_user_permissions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<authtoken_token> authtoken_token { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<base_adminlog> base_adminlog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<base_bookmark> base_bookmark { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<django_admin_log> django_admin_log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<guardian_userobjectpermission> guardian_userobjectpermission { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mobile_announcement> mobile_announcement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mobile_appnotification> mobile_appnotification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rest_framework_tracking_apirequestlog> rest_framework_tracking_apirequestlog { get; set; }
    }
}
