//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class base_sftpsetting
    {
        public int id { get; set; }
        public string host { get; set; }
        public int port { get; set; }
        public short is_sftp { get; set; }
        public string user_name { get; set; }
        public string user_password { get; set; }
        public string user_key { get; set; }
    }
}
