//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class base_whatsapplog
    {
        public int id { get; set; }
        public string receiver { get; set; }
        public string content { get; set; }
        public short result { get; set; }
        public System.DateTime push_time { get; set; }
        public string reason { get; set; }
    }
}
