//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class base_systemlog
    {
        public int id { get; set; }
        public System.DateTime execute_time { get; set; }
        public short operation { get; set; }
        public short execute_status { get; set; }
        public string description { get; set; }
    }
}
