//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class base_linenotifysetting
    {
        public int id { get; set; }
        public Nullable<int> include_sub_department { get; set; }
        public string line_notify_token { get; set; }
        public Nullable<int> message_type { get; set; }
        public string message_head { get; set; }
        public string message_tail { get; set; }
        public Nullable<System.DateTime> push_time { get; set; }
        public Nullable<int> is_valid { get; set; }
        public string remark { get; set; }
        public Nullable<int> line_notify_dept_id { get; set; }
    
        public virtual personnel_department personnel_department { get; set; }
    }
}
