//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class base_sysparamdept
    {
        public int id { get; set; }
        public string rule_name { get; set; }
        public int dept_id { get; set; }
        public string @operator { get; set; }
        public Nullable<System.DateTime> op_time { get; set; }
    }
}
