//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class base_eventalertsetting
    {
        public int id { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public string create_user { get; set; }
        public Nullable<System.DateTime> change_time { get; set; }
        public string change_user { get; set; }
        public short status { get; set; }
        public int event_id { get; set; }
        public string @event { get; set; }
        public string module { get; set; }
        public string sub_module { get; set; }
        public bool email_alert { get; set; }
        public bool app_alert { get; set; }
        public bool sms_alert { get; set; }
        public bool whatapp_alert { get; set; }
    }
}
