//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class base_bookmark
    {
        public int id { get; set; }
        public string title { get; set; }
        public string filters { get; set; }
        public bool is_share { get; set; }
        public System.DateTime time_saved { get; set; }
        public int content_type_id { get; set; }
        public Nullable<int> user_id { get; set; }
    
        public virtual auth_user auth_user { get; set; }
        public virtual django_content_type django_content_type { get; set; }
    }
}
