//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cal_ot
    {
        public int Id { get; set; }
        public int Employee_id { get; set; }
        public double ROT { get; set; }
        public int HOT { get; set; }
        public int WOT { get; set; }
        public System.DateTime OT_month { get; set; }
    
        public virtual master_file master_file { get; set; }
    }
}
