//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class certificatesavingtest_
    {
        public int Id { get; set; }
        public int employee_id { get; set; }
        public int certificate_type { get; set; }
        public string destination { get; set; }
        public Nullable<System.DateTime> submition_date { get; set; }
        public string cs_gr { get; set; }
    
        public virtual certificatetype certificatetype { get; set; }
        public virtual master_file master_file { get; set; }
    }
}
