//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CERTIFICATE_REQUEST
    {
        public int Id { get; set; }
        public Nullable<int> employee_id { get; set; }
        public string LETTER_TYPE { get; set; }
        public string MENTION_SALARY { get; set; }
        public string BL_bank_nane { get; set; }
        public string BL_account_no { get; set; }
        public string EL_name { get; set; }
        public string EL_purpose { get; set; }
        public Nullable<System.DateTime> EL_DOV_from { get; set; }
        public Nullable<System.DateTime> EL_DOV_to { get; set; }
        public Nullable<bool> TD_NCARREG { get; set; }
        public Nullable<bool> TD_CARREGREN { get; set; }
        public Nullable<bool> TD_DLA { get; set; }
        public Nullable<bool> TDLREN { get; set; }
        public string other { get; set; }
        public Nullable<bool> Etisalat { get; set; }
        public Nullable<bool> ADWEA { get; set; }
        public Nullable<bool> Mawaqif { get; set; }
        public Nullable<bool> Immigration { get; set; }
    
        public virtual master_file master_file { get; set; }
    }
}
