//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contract
    {
        [Display(Name = "contract ID")]
        public Nullable<int> con_id { get; set; }
        [Display(Name = "employee ID")]
        public int employee_no { get; set; }
        public string designation { get; set; }
        public string grade { get; set; }
        [Display(Name = "departmant project")]
        public string departmant_project { get; set; }
        [Display(Name = "salary details")]
        public Nullable<int> salary_details { get; set; }
        public Nullable<int> basic { get; set; }
        [Display(Name = "housing allowance")]
        public Nullable<int> housing_allowance { get; set; }
        [Display(Name = "transportation allowance")]
        public Nullable<int> transportation_allowance { get; set; }
        public Nullable<int> FOT { get; set; }
        [Display(Name = "food allowance")]
        public Nullable<int> food_allowance { get; set; }
        [Display(Name = "living allowance")]
        public Nullable<int> living_allowance { get; set; }
        [Display(Name = "ticket allowance")]
        public Nullable<int> ticket_allowance { get; set; }
        public Nullable<int> others { get; set; }
        public Nullable<int> arrears { get; set; }
        public int employee_id { get; set; }
        [Display(Name = "photo")]
        public string imgpath { get; set; }
        [Display(Name = "changed by")]
        public string changed_by { get; set; }
        [Display(Name = "date changed")]
        public System.DateTime date_changed { get; set; }

        public virtual master_file master_file { get; set; }
    }
}
