//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contract
    {
        [Display(Name = "Contract ID")]
        public Nullable<int> con_id { get; set; }
        [Display(Name = "Employee ID")]
        public int employee_no { get; set; }
        [Display(Name = "Designation")]
        public string designation { get; set; }
        public string grade { get; set; }
        [Display(Name = "Departmant Project")]
        public string departmant_project { get; set; }
        [Display(Name = "Salary Details")]
        public Nullable<int> salary_details { get; set; }
        [Display(Name = "Basic")]
        public Nullable<int> basic { get; set; }
        [Display(Name = "Housing Allowance")]
        public Nullable<int> housing_allowance { get; set; }
        [Display(Name = "Transportation Allowance")]
        public Nullable<int> transportation_allowance { get; set; }
        public Nullable<int> FOT { get; set; }
        [Display(Name = "Food Allowance")]
        public Nullable<int> food_allowance { get; set; }
        [Display(Name = "Living Allowance")]
        public Nullable<int> living_allowance { get; set; }
        [Display(Name = "Ticket Allowance")]
        public Nullable<int> ticket_allowance { get; set; }
        [Display(Name = "Other")]
        public Nullable<int> others { get; set; }
        [Display(Name = "Arrears")]
        public Nullable<int> arrears { get; set; }
        public int employee_id { get; set; }
        [Display(Name = "Photo")]
        public string imgpath { get; set; }
        [Display(Name = "Changed by")]
        public string changed_by { get; set; }
        [Display(Name = "Date changed")]
        public Nullable<System.DateTime> date_changed { get; set; }
    
        public virtual master_file master_file { get; set; }
    }
}
