//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contract
    {
        public Nullable<int> con_id { get; set; }
        public int employee_no { get; set; }
        public string designation { get; set; }
        public string grade { get; set; }
        public string departmant_project { get; set; }
        public Nullable<int> salary_details { get; set; }
        public Nullable<int> basic { get; set; }
        public Nullable<int> housing_allowance { get; set; }
        public Nullable<int> transportation_allowance { get; set; }
        public Nullable<int> FOT { get; set; }
        public Nullable<int> food_allowance { get; set; }
        public Nullable<int> living_allowance { get; set; }
        public Nullable<int> ticket_allowance { get; set; }
        public Nullable<int> others { get; set; }
        public Nullable<int> arrears { get; set; }
        public int employee_id { get; set; }
        public string imgpath { get; set; }
        public string changed_by { get; set; }
        public Nullable<System.DateTime> date_changed { get; set; }
    
        public virtual master_file master_file { get; set; }
    }
}
