//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detailsinarabic
    {
        public int Id { get; set; }
        public int employee_id { get; set; }
        public string ARname { get; set; }
        public string ARposition { get; set; }
        public string ARnationality { get; set; }
    
        public virtual master_file master_file { get; set; }
    }
}
