//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISCIPLINARY_ACTION_FORM
    {
        public int Id { get; set; }
        public Nullable<int> Employee_id { get; set; }
        public string TYPE_OF_ACTION { get; set; }
        public Nullable<System.DateTime> II_datetime { get; set; }
        public string II_location { get; set; }
        public string II_description { get; set; }
        public string II_witness { get; set; }
        public string II_polvio { get; set; }
        public string II_consequences { get; set; }
    
        public virtual master_file master_file { get; set; }
    }
}
