//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class django_celery_beat_crontabschedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public django_celery_beat_crontabschedule()
        {
            this.django_celery_beat_periodictask = new HashSet<django_celery_beat_periodictask>();
        }
    
        public int id { get; set; }
        public string minute { get; set; }
        public string hour { get; set; }
        public string day_of_week { get; set; }
        public string day_of_month { get; set; }
        public string month_of_year { get; set; }
        public string timezone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<django_celery_beat_periodictask> django_celery_beat_periodictask { get; set; }
    }
}
