//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DUTY_HANDOVER
    {
        public int Id { get; set; }

        [Display(Name = "Employee ID")]
        public Nullable<int> Employee_NO1 { get; set; }

        [Display(Name = "Employee ID")]
        public Nullable<int> Employee_NO2 { get; set; }

        [Display(Name = "Leave Starts on")]
        public Nullable<System.DateTime> leave_start { get; set; }

        [Display(Name = "Leave Ends on")]
        public Nullable<System.DateTime> leave_end { get; set; }
        [Display(Name = "Reason for Handover")]
        public string reason_for_handover { get; set; }
        public string RNR_HO1 { get; set; }
        public string RNR_HO2 { get; set; }
        public string RNR_HO3 { get; set; }
        public string RNR_HO4 { get; set; }
        public string RNR_HO5 { get; set; }

        [Display(Name = "Resuming on Duty")]
        public Nullable<System.DateTime> Resuming_on_Duty { get; set; }
    
        public virtual master_file master_file { get; set; }
        public virtual master_file master_file1 { get; set; }
    }
}
