//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class emirates_id
    {
        public int employee_id { get; set; }
        [Display(Name = "Employee ID")]
        public int employee_no { get; set; }
        [Display(Name = "EID no")]
        public int eid_no { get; set; }
        [Display(Name = " EID expiry")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:d}")]
        public System.DateTime eid_expiry { get; set; }
        [Display(Name = "Photo")]
        public string imgpath { get; set; }
        [Display(Name = "Changed by")]
        public string changed_by { get; set; }
        [Display(Name = "Date Changed")]
        public System.DateTime date_changed { get; set; }

        public virtual master_file master_file { get; set; }
    }
}
