//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class emirates_id
    {
        public int employee_id { get; set; }
        public int employee_no { get; set; }
        public long eid_no { get; set; }
        public System.DateTime eid_expiry { get; set; }
        public string imgpath { get; set; }
        public string changed_by { get; set; }
        public Nullable<System.DateTime> date_changed { get; set; }
    
        public virtual master_file master_file { get; set; }
    }
}
