//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class emp_joi_sta_change
    {
        public int Id { get; set; }
        public Nullable<int> Employee_id { get; set; }
        public string action_active { get; set; }
        public string New_Title { get; set; }
        public string Action_Taken { get; set; }
        public string Action_Taken2 { get; set; }
        public Nullable<long> Basic_Salary { get; set; }
        public Nullable<long> House_Rent_Allowance { get; set; }
        public Nullable<long> Telephone_Allowance { get; set; }
        public Nullable<long> Living_Allowance { get; set; }
        public Nullable<long> Transportation_Allowance { get; set; }
        public Nullable<long> Other_Allowances { get; set; }
        public Nullable<long> Total_Salary { get; set; }
        public string Medical_Insurance_Policy { get; set; }
        public string Annual_Leave { get; set; }
        public string Bank_Name_Branch { get; set; }
        public string Bank_Account_No { get; set; }
        public string Remarks { get; set; }
    
        public virtual master_file master_file { get; set; }
    }
}
