//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class empdayoff
    {
        public int Id { get; set; }
        public int emp_ID { get; set; }
        public System.DateTime date_off { get; set; }
        public System.DateTime date_added { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
        public string by_whom { get; set; }
    
        public virtual master_file master_file { get; set; }
    }
}
