//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class empreturnfromleavesub
    {
        public int Id { get; set; }
        [Display(Name = "Employee ID")]
        public int Employee_id { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd MMM yyyy}")]
        public System.DateTime Date { get; set; }
        public int leaveid { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd MMM yyyy}")]
        public Nullable<System.DateTime> actualreturnleave { get; set; }
        [Display(Name = "submitted by")]
        public string submitted_by { get; set; }
        [Display(Name = "approved by")]
        public string approved_byline { get; set; }
        [Display(Name = "approved by")]
        public string approved_byhod { get; set; }
        public string apstatus { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = false, DataFormatString = "{0:dd MMM yyyy}")]
        public Nullable<System.DateTime> dateadded { get; set; }
    
        public virtual Leave Leave { get; set; }
        public virtual master_file master_file { get; set; }
    }
}
