//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class end_of_service
    {
        public int Id { get; set; }
        public int Employee_id { get; set; }
        public Nullable<System.DateTime> last_working_day { get; set; }
        public string status { get; set; }
    
        public virtual master_file master_file { get; set; }
    }
}
