//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ep_epsetup
    {
        public int id { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public string create_user { get; set; }
        public Nullable<System.DateTime> change_time { get; set; }
        public string change_user { get; set; }
        public short status { get; set; }
        public bool temp_alarm { get; set; }
        public decimal temp_warning { get; set; }
        public Nullable<decimal> temp_warning_F { get; set; }
        public short temp_unit { get; set; }
        public bool mask_alarm { get; set; }
        public bool is_default { get; set; }
    }
}
