//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXIT_INTERVIEW
    {
        public int Id { get; set; }
        public string C1B { get; set; }
        public string C2B { get; set; }
        public string C3B { get; set; }
        public string C4B { get; set; }
        public string C5B { get; set; }
        public string C6B { get; set; }
        public string C7B { get; set; }
        public string C8B { get; set; }
    }
}
