//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FINAL_DEPARTURE_CLEARANCE
    {
        public int Id { get; set; }
        public Nullable<int> Employee_id { get; set; }
        public string f_Any_Advance { get; set; }
        public string f_Any_Advance_other { get; set; }
        public Nullable<System.DateTime> f_date { get; set; }
        public string IT_equipment { get; set; }
        public string IT_equipment_other { get; set; }
        public Nullable<System.DateTime> IT_date { get; set; }
        public string legal_poa { get; set; }
        public string legal_other { get; set; }
        public Nullable<System.DateTime> legal_date { get; set; }
        public string admin_equipment { get; set; }
        public string admin_other { get; set; }
        public Nullable<System.DateTime> admin_date { get; set; }
        public Nullable<System.DateTime> admin_camp_date { get; set; }
        public string iso_doc { get; set; }
        public string iso_other { get; set; }
        public Nullable<System.DateTime> iso_date { get; set; }
        public string line_man_doc { get; set; }
        public string line_man_other { get; set; }
        public Nullable<System.DateTime> line_man_date { get; set; }
        public string hr_docs { get; set; }
        public string hr_other { get; set; }
        public string Clearance_Details { get; set; }
        public Nullable<System.DateTime> hr_date { get; set; }
    }
}
