//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class formsuserdb
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> reqdate { get; set; }
        public Nullable<int> form_id { get; set; }
        public string subtablename { get; set; }
        public Nullable<int> subtablerec_id { get; set; }
        public string status { get; set; }
        public Nullable<int> emp_id { get; set; }
    
        public virtual Form Form { get; set; }
        public virtual master_file master_file { get; set; }
    }
}
