//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRA_requset
    {
        public int Id { get; set; }
        public Nullable<int> Employee_id { get; set; }
        public Nullable<int> Amonths { get; set; }
        public Nullable<System.DateTime> OTdate { get; set; }
        public string remarks { get; set; }
        public Nullable<long> BS { get; set; }
        public Nullable<long> house_RA { get; set; }
        public string HRA_advance_com { get; set; }
    }
}
