//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.Entity.Validation;
using System.Linq;

namespace HRworks.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HREntities : DbContext
    {
        
        public HREntities()
            : base("name=HREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<bank_details> bank_details { get; set; }
        public virtual DbSet<contract> contracts { get; set; }
        public virtual DbSet<emirates_id> emirates_id { get; set; }
        public virtual DbSet<insurance> insurances { get; set; }
        public virtual DbSet<Leave> Leaves { get; set; }
        public virtual DbSet<master_file> master_file { get; set; }
        public virtual DbSet<passport> passports { get; set; }
        public virtual DbSet<Table> Tables { get; set; }
        public virtual DbSet<username> usernames { get; set; }
        public virtual DbSet<visa_and_labour_card> visa_and_labour_card { get; set; }
        public override int SaveChanges()
        {
            try
            {
                return base.SaveChanges();
            }
            catch (DbEntityValidationException ex)
            {
                // Retrieve the error messages as a list of strings.
                var errorMessages = ex.EntityValidationErrors
                    .SelectMany(x => x.ValidationErrors)
                    .Select(x => x.ErrorMessage);

                // Join the list to a single string.
                var fullErrorMessage = string.Concat(errorMessages);

                // Combine the original exception message with the new one.
                var exceptionMessage = string.Concat(ex.Message + "The validation errors are: " + fullErrorMessage);

                // Throw a new DbEntityValidationException with the improved exception message.
                throw new DbEntityValidationException(exceptionMessage, ex.EntityValidationErrors);
            }
        }
    }
}
