//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HREntities : DbContext
    {
        public HREntities()
            : base("name=HREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<absencelist> absencelists { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<ATTENDANCE_ADJUSTMENT> ATTENDANCE_ADJUSTMENT { get; set; }
        public virtual DbSet<bank_details> bank_details { get; set; }
        public virtual DbSet<business_trip> business_trip { get; set; }
        public virtual DbSet<BUSINESS_TRIP_REPORT_> BUSINESS_TRIP_REPORT_ { get; set; }
        public virtual DbSet<CERTIFICATE_REQUEST> CERTIFICATE_REQUEST { get; set; }
        public virtual DbSet<certificatesavingtest_> certificatesavingtest_ { get; set; }
        public virtual DbSet<certificatetype> certificatetypes { get; set; }
        public virtual DbSet<contract> contracts { get; set; }
        public virtual DbSet<contractlogin> contractlogins { get; set; }
        public virtual DbSet<detailsinarabic> detailsinarabics { get; set; }
        public virtual DbSet<DISCIPLINARY_ACTION_FORM> DISCIPLINARY_ACTION_FORM { get; set; }
        public virtual DbSet<DUTY_HANDOVER> DUTY_HANDOVER { get; set; }
        public virtual DbSet<emirates_id> emirates_id { get; set; }
        public virtual DbSet<emp_joi_sta_change> emp_joi_sta_change { get; set; }
        public virtual DbSet<employeeleavesubmition> employeeleavesubmitions { get; set; }
        public virtual DbSet<emprel> emprels { get; set; }
        public virtual DbSet<empreturnfromleavesub> empreturnfromleavesubs { get; set; }
        public virtual DbSet<end_of_service> end_of_service { get; set; }
        public virtual DbSet<EXIT_INTERVIEW> EXIT_INTERVIEW { get; set; }
        public virtual DbSet<FINAL_DEPARTURE_CLEARANCE> FINAL_DEPARTURE_CLEARANCE { get; set; }
        public virtual DbSet<hik> hiks { get; set; }
        public virtual DbSet<HRA_requset> HRA_requset { get; set; }
        public virtual DbSet<induction_training> induction_training { get; set; }
        public virtual DbSet<insurance> insurances { get; set; }
        public virtual DbSet<JOB_INTERVIEW_EVALUATION> JOB_INTERVIEW_EVALUATION { get; set; }
        public virtual DbSet<labour_card> labour_card { get; set; }
        public virtual DbSet<lbperyear> lbperyears { get; set; }
        public virtual DbSet<Leave> Leaves { get; set; }
        public virtual DbSet<leave_absence> leave_absence { get; set; }
        public virtual DbSet<Leave_approved> Leave_approved { get; set; }
        public virtual DbSet<leavecal> leavecals { get; set; }
        public virtual DbSet<leavecal2020> leavecal2020 { get; set; }
        public virtual DbSet<leavecalperyear> leavecalperyears { get; set; }
        public virtual DbSet<liqiapproval> liqiapprovals { get; set; }
        public virtual DbSet<liquidation> liquidations { get; set; }
        public virtual DbSet<liquidation_ref> liquidation_ref { get; set; }
        public virtual DbSet<liquiexp> liquiexps { get; set; }
        public virtual DbSet<MANPOWER_TRANSFER_REQUEST> MANPOWER_TRANSFER_REQUEST { get; set; }
        public virtual DbSet<master_file> master_file { get; set; }
        public virtual DbSet<OT_employee_list> OT_employee_list { get; set; }
        public virtual DbSet<OVERTIME_APPROVAL> OVERTIME_APPROVAL { get; set; }
        public virtual DbSet<passport> passports { get; set; }
        public virtual DbSet<payrole> payroles { get; set; }
        public virtual DbSet<payrolelogin> payrolelogins { get; set; }
        public virtual DbSet<payrollsaved> payrollsaveds { get; set; }
        public virtual DbSet<PROBATION_ASSESSMENT> PROBATION_ASSESSMENT { get; set; }
        public virtual DbSet<rec_req_form> rec_req_form { get; set; }
        public virtual DbSet<Table> Tables { get; set; }
        public virtual DbSet<Training_Effectiveness> Training_Effectiveness { get; set; }
        public virtual DbSet<Training_Evaluation> Training_Evaluation { get; set; }
        public virtual DbSet<Training_Request> Training_Request { get; set; }
        public virtual DbSet<username> usernames { get; set; }
        public virtual DbSet<visa> visas { get; set; }
        public virtual DbSet<visa_and_labour_card> visa_and_labour_card { get; set; }
        public virtual DbSet<certificatesavinggrove> certificatesavinggroves { get; set; }
        public virtual DbSet<companLeaveR> companLeaveRs { get; set; }
        public virtual DbSet<companleaveBal> companleaveBals { get; set; }
        public virtual DbSet<HRprojectlist> HRprojectlists { get; set; }
        public virtual DbSet<project_attendence> project_attendence { get; set; }
        public virtual DbSet<absexception> absexceptions { get; set; }
        public virtual DbSet<cal_lwop> cal_lwop { get; set; }
        public virtual DbSet<cal_ot> cal_ot { get; set; }
        public virtual DbSet<calab> calabs { get; set; }
        public virtual DbSet<HRotapp> HRotapps { get; set; }
        public virtual DbSet<HRweekend> HRweekends { get; set; }
    }
}
