//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRotapp
    {
        public int Id { get; set; }
        public int Employee_id { get; set; }
        public System.DateTime otdate { get; set; }
        public int othrs { get; set; }
        public string sumby { get; set; }
        public string appby { get; set; }
        public string reason { get; set; }
        public string status { get; set; }
        public System.DateTime dateadded { get; set; }
        public System.DateTime datemodfied { get; set; }
    
        public virtual master_file master_file { get; set; }
    }
}
