//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRweekend
    {
        public int Id { get; set; }
        public int pro_id { get; set; }
        public System.DateTime dweek { get; set; }
        public System.DateTime wdate { get; set; }
    
        public virtual HRprojectlist HRprojectlist { get; set; }
    }
}
