//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class iclock_publicmessage
    {
        public int id { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public string create_user { get; set; }
        public Nullable<System.DateTime> change_time { get; set; }
        public string change_user { get; set; }
        public short status { get; set; }
        public Nullable<System.DateTime> last_send { get; set; }
        public Nullable<int> message_id { get; set; }
        public int terminal_id { get; set; }
    
        public virtual iclock_shortmessage iclock_shortmessage { get; set; }
        public virtual iclock_terminal iclock_terminal { get; set; }
    }
}
