//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class iclock_terminallog
    {
        public int id { get; set; }
        public Nullable<short> terminal_tz { get; set; }
        public string admin { get; set; }
        public Nullable<short> action_name { get; set; }
        public Nullable<System.DateTime> action_time { get; set; }
        public string @object { get; set; }
        public Nullable<int> param1 { get; set; }
        public Nullable<int> param2 { get; set; }
        public Nullable<int> param3 { get; set; }
        public Nullable<System.DateTime> upload_time { get; set; }
        public int terminal_id { get; set; }
    
        public virtual iclock_terminal iclock_terminal { get; set; }
    }
}
