//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class iclock_shortmessage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public iclock_shortmessage()
        {
            this.iclock_privatemessage = new HashSet<iclock_privatemessage>();
            this.iclock_publicmessage = new HashSet<iclock_publicmessage>();
        }
    
        public int id { get; set; }
        public string message { get; set; }
        public System.DateTime start_time { get; set; }
        public int duration { get; set; }
        public string msg_type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<iclock_privatemessage> iclock_privatemessage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<iclock_publicmessage> iclock_publicmessage { get; set; }
    }
}
