//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class iclock_transactionproofcmd
    {
        public int id { get; set; }
        public System.DateTime action_time { get; set; }
        public System.DateTime start_time { get; set; }
        public System.DateTime end_time { get; set; }
        public Nullable<int> terminal_count { get; set; }
        public Nullable<int> server_count { get; set; }
        public Nullable<short> flag { get; set; }
        public Nullable<int> reserved_init { get; set; }
        public Nullable<double> reserved_float { get; set; }
        public string reserved_char { get; set; }
        public int terminal_id { get; set; }
    
        public virtual iclock_terminal iclock_terminal { get; set; }
    }
}
