//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class iclock_transaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public iclock_transaction()
        {
            this.att_payloadeffectpunch = new HashSet<att_payloadeffectpunch>();
            this.att_payloadparing = new HashSet<att_payloadparing>();
            this.att_payloadparing1 = new HashSet<att_payloadparing>();
            this.att_payloadpunch = new HashSet<att_payloadpunch>();
            this.att_payloadtimecard = new HashSet<att_payloadtimecard>();
            this.att_payloadtimecard1 = new HashSet<att_payloadtimecard>();
        }
    
        public int id { get; set; }
        public string emp_code { get; set; }
        public System.DateTime punch_time { get; set; }
        public string punch_state { get; set; }
        public int verify_type { get; set; }
        public string work_code { get; set; }
        public string terminal_sn { get; set; }
        public string terminal_alias { get; set; }
        public string area_alias { get; set; }
        public Nullable<double> longitude { get; set; }
        public Nullable<double> latitude { get; set; }
        public string gps_location { get; set; }
        public string mobile { get; set; }
        public Nullable<short> source { get; set; }
        public Nullable<short> purpose { get; set; }
        public string crc { get; set; }
        public Nullable<short> is_attendance { get; set; }
        public string reserved { get; set; }
        public Nullable<System.DateTime> upload_time { get; set; }
        public Nullable<short> sync_status { get; set; }
        public Nullable<System.DateTime> sync_time { get; set; }
        public Nullable<short> is_mask { get; set; }
        public Nullable<decimal> temperature { get; set; }
        public Nullable<int> emp_id { get; set; }
        public Nullable<int> terminal_id { get; set; }
        public string company_code { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<att_payloadeffectpunch> att_payloadeffectpunch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<att_payloadparing> att_payloadparing { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<att_payloadparing> att_payloadparing1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<att_payloadpunch> att_payloadpunch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<att_payloadtimecard> att_payloadtimecard { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<att_payloadtimecard> att_payloadtimecard1 { get; set; }
        public virtual iclock_terminal iclock_terminal { get; set; }
        public virtual personnel_employee personnel_employee { get; set; }
    }
}
