//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class iclock_errorcommandlog
    {
        public int id { get; set; }
        public string error_code { get; set; }
        public string error_msg { get; set; }
        public string data_origin { get; set; }
        public string cmd { get; set; }
        public string additional { get; set; }
        public System.DateTime upload_time { get; set; }
        public int terminal_id { get; set; }
    
        public virtual iclock_terminal iclock_terminal { get; set; }
    }
}
