//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class iclock_terminalcommand
    {
        public int id { get; set; }
        public string content { get; set; }
        public System.DateTime commit_time { get; set; }
        public Nullable<System.DateTime> transfer_time { get; set; }
        public Nullable<System.DateTime> return_time { get; set; }
        public Nullable<int> return_value { get; set; }
        public Nullable<int> package { get; set; }
        public int terminal_id { get; set; }
    
        public virtual iclock_terminal iclock_terminal { get; set; }
    }
}
