//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class induction_training
    {
        public int Id { get; set; }
        public Nullable<int> employee_id { get; set; }
        public bool C1a { get; set; }
        public bool C2a { get; set; }
        public bool C3a { get; set; }
        public bool C4a { get; set; }
        public bool C5a { get; set; }
        public bool C6a { get; set; }
        public bool C7a { get; set; }
        public bool C8a { get; set; }
        public bool C9a { get; set; }
    
        public virtual master_file master_file { get; set; }
    }
}
