//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class insurance
    {
        public int employee_id { get; set; }
        [Display(Name = "employee ID")]
        public int employee_no { get; set; }
        [Display(Name = "card no")]
        public Nullable<int> card_no { get; set; }
        [Display(Name = "DOB")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:d}")]
        public Nullable<System.DateTime> dob { get; set; }
        public Nullable<int> age { get; set; }
        public string gender { get; set; }
        public string dependency { get; set; }
        [Display(Name = "marital status")]
        public string marital_status { get; set; }
        public string nationality { get; set; }
        [Display(Name = "EID no")]
        public Nullable<int> eid_no { get; set; }
        [Display(Name = "pasport no")]
        public Nullable<int> pasport_no { get; set; }
        [Display(Name = " UID no")]
        public Nullable<int> uid_no { get; set; }
        [Display(Name = "emitae visa issue")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:d}")]
        public Nullable<System.DateTime> emitae_visa_issue { get; set; }
        [Display(Name = "annual primium")]
        public Nullable<int> annual_primium { get; set; }
        [Display(Name = "deletion date")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:d}")]
        public Nullable<System.DateTime> deletion_date { get; set; }
        [Display(Name = "invoice no")]
        public Nullable<int> invoice_no { get; set; }
        [Display(Name = "credit amt")]
        public Nullable<int> credit_amt { get; set; }
        [Display(Name = "photo")]
        public string imgpath { get; set; }
        [Display(Name = "changed by")]
        public string changed_by { get; set; }
        [Display(Name = "date changed")]
        public Nullable<System.DateTime> date_changed { get; set; }


        public virtual master_file master_file { get; set; }
    }
}
