//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class insurance
    {
        public int employee_id { get; set; }
        public int employee_no { get; set; }
        public Nullable<int> card_no { get; set; }
        public Nullable<int> age { get; set; }
        public string dependency { get; set; }
        public string marital_status { get; set; }
        public Nullable<int> annual_primium { get; set; }
        public Nullable<System.DateTime> deletion_date { get; set; }
        public Nullable<int> invoice_no { get; set; }
        public Nullable<int> credit_amt { get; set; }
        public string imgpath { get; set; }
        public string changed_by { get; set; }
        public Nullable<System.DateTime> date_changed { get; set; }
    
        public virtual master_file master_file { get; set; }
    }
}
