//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lbperyear
    {
        public int Id { get; set; }
        public int Employee_id { get; set; }
        public int total_leave_balance { get; set; }
        public System.DateTime year { get; set; }
        public System.DateTime date_updated { get; set; }
        public System.DateTime modified_date { get; set; }
    
        public virtual master_file master_file { get; set; }
    }
}
