//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Leave
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Leave()
        {
            this.payroles = new HashSet<payrole>();
        }

        [Display(Name = "Employee ID")]
        public int Employee_id { get; set; }

        public int Id { get; set; }

        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd MMM yyyy}")]
        public System.DateTime Date { get; set; }

        public string Reference { get; set; }

        [Display(Name = "from")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd MMM yyyy}")]
        public Nullable<System.DateTime> Start_leave { get; set; }

        [Display(Name = "to")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd MMM yyyy}")]
        public Nullable<System.DateTime> End_leave { get; set; }

        [Display(Name = "Return leave")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd MMM yyyy}")]
        public Nullable<System.DateTime> Return_leave { get; set; }

        [Display(Name = "leave type")]
        public string leave_type { get; set; }

        [Display(Name = "actual_return_date")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd MMM yyyy}")]
        public Nullable<System.DateTime> actual_return_date { get; set; }

        public Nullable<double> toltal_requested_days { get; set; }

        public Nullable<bool> leave_salary { get; set; }

        public Nullable<long> mobile_no { get; set; }

        public string email { get; set; }

        public Nullable<double> leave_bal { get; set; }

        public string submitted_by { get; set; }

        public string approved_by { get; set; }

        public Nullable<System.DateTime> time { get; set; }

        public Nullable<int> days { get; set; }

        public string data_o_n { get; set; }

        [Display(Name = "is half-day included")]
        public bool half { get; set; }
        public string actualchangedby { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd MMM yyyy}")]
        public Nullable<System.DateTime> actualchangeddateby { get; set; }
        public string approved_byHR { get; set; }
        public string apstatus { get; set; }
        public string imgpath { get; set; }
    
        public virtual master_file master_file { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<payrole> payroles { get; set; }
    }
}
