//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class leavecal
    {
        public int Id { get; set; }
        public Nullable<int> Employee_id { get; set; }
        public Nullable<double> leave_balance { get; set; }
        public Nullable<double> period { get; set; }
        public Nullable<double> anual_leave_taken { get; set; }
        public Nullable<double> unpaid_leave { get; set; }
        public Nullable<double> net_period { get; set; }
        public Nullable<double> accrued { get; set; }
    
        public virtual master_file master_file { get; set; }
    }
}
