//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leave
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public string Reference { get; set; }
        public System.DateTime Start_leave { get; set; }
        public Nullable<System.DateTime> End_leave { get; set; }
        public Nullable<System.DateTime> Return_leave { get; set; }
        public int Employee_id { get; set; }
        public string leave_type { get; set; }
        public Nullable<System.DateTime> actual_return_date { get; set; }
    
        public virtual master_file master_file { get; set; }
    }
}
