//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class leavecalperyear
    {
        public int Id { get; set; }
        public int Employee_id { get; set; }
        public System.DateTime balances_of_year { get; set; }
        public Nullable<double> period { get; set; }
        public Nullable<double> unpaid { get; set; }
        public Nullable<double> net_period { get; set; }
        public Nullable<double> accrued { get; set; }
        public Nullable<double> annual_leave_taken { get; set; }
        public Nullable<double> Annual_Leave_Applied { get; set; }
        public Nullable<double> Annual_Leave_total { get; set; }
        public Nullable<double> leave_balance { get; set; }
        public Nullable<double> forfited_balance { get; set; }
        public Nullable<double> sick_leave_balance { get; set; }
        public Nullable<double> compassionate_leave_balance { get; set; }
        public Nullable<double> maternity_leave_balance { get; set; }
        public Nullable<double> haj_leave_balance { get; set; }
        public Nullable<double> UDDAH_leave_balance { get; set; }
        public Nullable<double> escort_leave_balance { get; set; }
        public Nullable<double> paternity_leave_balance { get; set; }
        public Nullable<double> sabbatical_leave_balance { get; set; }
        public Nullable<double> study_leave_balance { get; set; }
        public System.DateTime date_updated { get; set; }
    
        public virtual master_file master_file { get; set; }
    }
}
