//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class leave_absence
    {
        public Nullable<int> Employee_id { get; set; }
        public int Id { get; set; }
        public Nullable<double> absence { get; set; }

        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MMM yyyy}")]
        public Nullable<System.DateTime> month { get; set; }
    
        public virtual master_file master_file { get; set; }
    }
}
