//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class leavecal2020
    {
        public int Id { get; set; }
        public Nullable<int> Employee_id { get; set; }
        public Nullable<double> leave_balance { get; set; }
        public Nullable<double> periodtill2020 { get; set; }
        public Nullable<double> anual_leave_takentill2020 { get; set; }
        public Nullable<double> unpaid_leavetill2020 { get; set; }
        public Nullable<double> net_periodtill2020 { get; set; }
        public Nullable<double> accruedtill2020 { get; set; }
        public Nullable<double> forfitedtill2020 { get; set; }
        public Nullable<double> periodafter2020 { get; set; }
        public Nullable<double> anual_leave_takenafter2020 { get; set; }
        public Nullable<double> unpaid_leaveafter2020 { get; set; }
        public Nullable<double> net_periodafter2020 { get; set; }
        public Nullable<double> accruedafter2020 { get; set; }
        public Nullable<double> forfitedafter2020 { get; set; }
        public Nullable<System.DateTime> dateupdated { get; set; }
        public Nullable<double> ifslbal { get; set; }
    
        public virtual master_file master_file { get; set; }
    }
}
