//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class liquidation
    {
        public int Id { get; set; }
        [Display(Name = "bill no")]
        public Nullable<long> bill_no { get; set; }
        public string expenses { get; set; }
        public Nullable<System.DateTime> invoice_date { get; set; }
        [DataType(DataType.MultilineText)]
        public string discription { get; set; }
        [Display(Name = "Employee NO")]
        public Nullable<int> employee_no { get; set; }
        public Nullable<long> MBNo { get; set; }
        [Display(Name = "invoice (vat exclusive)")]
        public Nullable<decimal> invoice { get; set; }
        [Display(Name = "VAT charge")]
        public Nullable<decimal> VAT { get; set; }
        [Display(Name = "invoice amount")]
        public Nullable<decimal> invoice_amount { get; set; }
        public Nullable<long> refr { get; set; }
        public string changed_by { get; set; }
        public Nullable<System.DateTime> date_changed { get; set; }
    
        public virtual master_file master_file { get; set; }
        public virtual liquidation_ref liquidation_ref { get; set; }
    }
}
