//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class MANPOWER_TRANSFER_REQUEST
    {
        public int Id { get; set; }

        [Display(Name = "Employee ID")]
        public Nullable<int> Employee_id { get; set; }

        [Display(Name = "request date")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd MMM yyyy}")]
        public Nullable<System.DateTime> request_date { get; set; }

        [Display(Name = "from")]
        public string pro_from { get; set; }

        [Display(Name = "to")]
        public string por_to { get; set; }

        [Display(Name = "effective date")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd MMM yyyy}")]
        public Nullable<System.DateTime> effective_date { get; set; }
        public string remarks { get; set; }
    
        public virtual master_file master_file { get; set; }
    }
}
