//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class master_file
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public master_file()
        {
            this.bank_details = new HashSet<bank_details>();
            this.contracts = new HashSet<contract>();
            this.emirates_id = new HashSet<emirates_id>();
            this.insurances = new HashSet<insurance>();
            this.Leaves = new HashSet<Leave>();
            this.liquidations = new HashSet<liquidation>();
            this.passports = new HashSet<passport>();
            this.visa_and_labour_card = new HashSet<visa_and_labour_card>();
        }
    
        public int employee_id { get; set; }
        public int employee_no { get; set; }
        public string employee_name { get; set; }
        public string nationality { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public Nullable<System.DateTime> date_joined { get; set; }
        public Nullable<System.DateTime> last_working_day { get; set; }
        public string gender { get; set; }
        public string status { get; set; }
        public Nullable<long> person_code { get; set; }
        public string img { get; set; }
        public string changed_by { get; set; }
        public Nullable<System.DateTime> date_changed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bank_details> bank_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<contract> contracts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<emirates_id> emirates_id { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<insurance> insurances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Leave> Leaves { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<liquidation> liquidations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<passport> passports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<visa_and_labour_card> visa_and_labour_card { get; set; }
    }
}
