//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class master_file
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public master_file()
        {
            this.bank_details = new HashSet<bank_details>();
            this.contracts = new HashSet<contract>();
            this.emirates_id = new HashSet<emirates_id>();
            this.insurances = new HashSet<insurance>();
            this.labour_card = new HashSet<labour_card>();
            this.Leaves = new HashSet<Leave>();
            this.liquidations = new HashSet<liquidation>();
            this.passports = new HashSet<passport>();
            this.visa_and_labour_card = new HashSet<visa_and_labour_card>();
            this.visas = new HashSet<visa>();
            this.Leave_approved = new HashSet<Leave_approved>();
            this.leavecals = new HashSet<leavecal>();
            this.leave_absence = new HashSet<leave_absence>();
            this.ATTENDANCE_ADJUSTMENT = new HashSet<ATTENDANCE_ADJUSTMENT>();
            this.BUSINESS_TRIP_REPORT_ = new HashSet<BUSINESS_TRIP_REPORT_>();
            this.CERTIFICATE_REQUEST = new HashSet<CERTIFICATE_REQUEST>();
            this.DUTY_HANDOVER = new HashSet<DUTY_HANDOVER>();
            this.DUTY_HANDOVER1 = new HashSet<DUTY_HANDOVER>();
            this.induction_training = new HashSet<induction_training>();
            this.MANPOWER_TRANSFER_REQUEST = new HashSet<MANPOWER_TRANSFER_REQUEST>();
            this.OT_employee_list = new HashSet<OT_employee_list>();
            this.PROBATION_ASSESSMENT = new HashSet<PROBATION_ASSESSMENT>();
            this.Training_Effectiveness = new HashSet<Training_Effectiveness>();
            this.Training_Evaluation = new HashSet<Training_Evaluation>();
            this.Training_Request = new HashSet<Training_Request>();
            this.end_of_service = new HashSet<end_of_service>();
            this.emp_joi_sta_change = new HashSet<emp_joi_sta_change>();
            this.payroles = new HashSet<payrole>();
        }
    
        public int employee_id { get; set; }

        [Display(Name = "Employee NO")]
        public int employee_no { get; set; }

        [Display(Name = "Employee Name")]
        public string employee_name { get; set; }

        public string nationality { get; set; }

        [Display(Name = "DOB")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd MMM yyyy}")]
        public Nullable<System.DateTime> dob { get; set; }

        [Display(Name = "Date Joined")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd MMM yyyy}")]
        public Nullable<System.DateTime> date_joined { get; set; }

        [Display(Name = "Last Working Day")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd MMM yyyy}")]
        public Nullable<System.DateTime> last_working_day { get; set; }

        public string gender { get; set; }

        public string status { get; set; }

        [Display(Name = "personcode")]
        public Nullable<long> person_code { get; set; }

        [Display(Name = "Photo")]
        public string img { get; set; }

        [Display(Name = "Changed By")]
        public string changed_by { get; set; }

        [Display(Name = "Date Changed")]
        public Nullable<System.DateTime> date_changed { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bank_details> bank_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<contract> contracts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<emirates_id> emirates_id { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<insurance> insurances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<labour_card> labour_card { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Leave> Leaves { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<liquidation> liquidations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<passport> passports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<visa_and_labour_card> visa_and_labour_card { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<visa> visas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Leave_approved> Leave_approved { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<leavecal> leavecals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<leave_absence> leave_absence { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATTENDANCE_ADJUSTMENT> ATTENDANCE_ADJUSTMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BUSINESS_TRIP_REPORT_> BUSINESS_TRIP_REPORT_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CERTIFICATE_REQUEST> CERTIFICATE_REQUEST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DUTY_HANDOVER> DUTY_HANDOVER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DUTY_HANDOVER> DUTY_HANDOVER1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<induction_training> induction_training { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MANPOWER_TRANSFER_REQUEST> MANPOWER_TRANSFER_REQUEST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OT_employee_list> OT_employee_list { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROBATION_ASSESSMENT> PROBATION_ASSESSMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Training_Effectiveness> Training_Effectiveness { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Training_Evaluation> Training_Evaluation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Training_Request> Training_Request { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<end_of_service> end_of_service { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<emp_joi_sta_change> emp_joi_sta_change { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<payrole> payroles { get; set; }
    }
}
