//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class master_file
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public master_file()
        {
            this.contracts = new HashSet<contract>();
            this.emirates_id = new HashSet<emirates_id>();
            this.insurances = new HashSet<insurance>();
            this.Leaves = new HashSet<Leave>();
            this.passports = new HashSet<passport>();
            this.visa_and_labour_card = new HashSet<visa_and_labour_card>();
        }

        public int employee_id { get; set; }
        [Display(Name = "Employee NO")]
        public int employee_no { get; set; }
        [Display(Name = "Employee Name")]
        public string employee_name { get; set; }
        public string nationality { get; set; }
        [Display(Name = "DOB")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:d}")]
        public Nullable<System.DateTime> dob { get; set; }
        [Display(Name = "Date Joined")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:d}")]
        public Nullable<System.DateTime> date_joined { get; set; }
        [Display(Name = "Last Working Day")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:d}")]
        public Nullable<System.DateTime> last_working_day { get; set; }
        public string gender { get; set; }
        public string IBAN { get; set; }
        [Display(Name = "Account No")]
        public Nullable<long> account_no { get; set; }
        [Display(Name = "Bank Name")]
        public string bank_name { get; set; }
        public string status { get; set; }
        [Display(Name = "Photo")]
        public string img { get; set; }
        [Display(Name = "Changed By")]
        public string changed_by { get; set; }
        [Display(Name = "Date Changed")]
        public System.DateTime date_changed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<contract> contracts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<emirates_id> emirates_id { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<insurance> insurances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Leave> Leaves { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<passport> passports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<visa_and_labour_card> visa_and_labour_card { get; set; }
    }
}
