//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class meeting_meetingroomdevice
    {
        public int id { get; set; }
        public int device_id { get; set; }
        public Nullable<int> room_id { get; set; }
    
        public virtual iclock_terminal iclock_terminal { get; set; }
        public virtual meeting_meetingroom meeting_meetingroom { get; set; }
    }
}
