//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class meeting_meetingentity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public meeting_meetingentity()
        {
            this.meeting_meetingentity_attender = new HashSet<meeting_meetingentity_attender>();
            this.meeting_meetingmanuallog = new HashSet<meeting_meetingmanuallog>();
            this.meeting_meetingpayloadbase = new HashSet<meeting_meetingpayloadbase>();
            this.meeting_meetingtransaction = new HashSet<meeting_meetingtransaction>();
        }
    
        public int workflowinstance_ptr_id { get; set; }
        public string code { get; set; }
        public string alias { get; set; }
        public string content { get; set; }
        public System.DateTime meeting_date { get; set; }
        public System.DateTime start_time { get; set; }
        public System.DateTime end_time { get; set; }
        public int duration { get; set; }
        public bool in_required { get; set; }
        public System.DateTime in_start { get; set; }
        public System.DateTime in_end { get; set; }
        public bool out_required { get; set; }
        public System.DateTime out_start { get; set; }
        public System.DateTime out_end { get; set; }
        public bool enable_virtual { get; set; }
        public string virutal_uuid { get; set; }
        public short time_zone { get; set; }
        public string preferences { get; set; }
        public string link_data { get; set; }
        public string apply_reason { get; set; }
        public System.DateTime apply_time { get; set; }
        public Nullable<System.DateTime> calculation_time { get; set; }
        public Nullable<System.DateTime> sync_time { get; set; }
        public System.DateTime view_date { get; set; }
        public bool host_video { get; set; }
        public bool participant_video { get; set; }
        public bool enable_waiting_room { get; set; }
        public bool jbh_anytime { get; set; }
        public bool mute_upon_entry { get; set; }
        public string auto_recording { get; set; }
        public Nullable<int> room_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<meeting_meetingentity_attender> meeting_meetingentity_attender { get; set; }
        public virtual meeting_meetingroom meeting_meetingroom { get; set; }
        public virtual workflow_workflowinstance workflow_workflowinstance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<meeting_meetingmanuallog> meeting_meetingmanuallog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<meeting_meetingpayloadbase> meeting_meetingpayloadbase { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<meeting_meetingtransaction> meeting_meetingtransaction { get; set; }
    }
}
