//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class meeting_meetingmanuallog
    {
        public int workflowinstance_ptr_id { get; set; }
        public System.DateTime punch_time { get; set; }
        public string punch_state { get; set; }
        public string apply_reason { get; set; }
        public System.DateTime apply_time { get; set; }
        public Nullable<int> meeting_id { get; set; }
    
        public virtual meeting_meetingentity meeting_meetingentity { get; set; }
        public virtual workflow_workflowinstance workflow_workflowinstance { get; set; }
    }
}
