//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class meeting_meetingtransaction
    {
        public int id { get; set; }
        public string emp_code { get; set; }
        public System.DateTime punch_datetime { get; set; }
        public System.DateTime punch_date { get; set; }
        public System.DateTime punch_time { get; set; }
        public string punch_state { get; set; }
        public short source { get; set; }
        public System.DateTime upload_time { get; set; }
        public Nullable<int> emp_id { get; set; }
        public Nullable<int> meeting_id { get; set; }
        public Nullable<int> terminal_id { get; set; }
    
        public virtual iclock_terminal iclock_terminal { get; set; }
        public virtual meeting_meetingentity meeting_meetingentity { get; set; }
        public virtual personnel_employee personnel_employee { get; set; }
    }
}
