//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class meeting_meetingpayloadbase
    {
        public string id { get; set; }
        public System.DateTime start_time { get; set; }
        public System.DateTime end_time { get; set; }
        public int duration { get; set; }
        public System.DateTime meeting_date { get; set; }
        public Nullable<System.DateTime> clock_in { get; set; }
        public Nullable<System.DateTime> clock_out { get; set; }
        public int attended_duration { get; set; }
        public int late_in { get; set; }
        public int early_out { get; set; }
        public int absent { get; set; }
        public int emp_id { get; set; }
        public int meeting_id { get; set; }
    
        public virtual meeting_meetingentity meeting_meetingentity { get; set; }
        public virtual personnel_employee personnel_employee { get; set; }
    }
}
