//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mobile_appactionlog
    {
        public int id { get; set; }
        public string user { get; set; }
        public string client { get; set; }
        public string action { get; set; }
        public string @params { get; set; }
        public string describe { get; set; }
        public short request_status { get; set; }
        public System.DateTime action_time { get; set; }
        public string remote_ip { get; set; }
    }
}
