//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mobile_applist
    {
        public int id { get; set; }
        public string username { get; set; }
        public System.DateTime login_time { get; set; }
        public System.DateTime last_active { get; set; }
        public string token { get; set; }
        public string device_token { get; set; }
        public string client_id { get; set; }
        public short client_category { get; set; }
        public Nullable<short> active { get; set; }
        public Nullable<short> enable { get; set; }
    }
}
