//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mobile_announcement
    {
        public int id { get; set; }
        public string subject { get; set; }
        public string content { get; set; }
        public short category { get; set; }
        public string sender { get; set; }
        public string system_sender { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public Nullable<int> admin_id { get; set; }
        public Nullable<int> init_sender_id { get; set; }
        public Nullable<int> receiver_id { get; set; }
    
        public virtual auth_user auth_user { get; set; }
        public virtual personnel_employee personnel_employee { get; set; }
        public virtual personnel_employee personnel_employee1 { get; set; }
    }
}
