//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mobile_gpsfordepartment_location
    {
        public int id { get; set; }
        public int gpsfordepartment_id { get; set; }
        public int gpslocation_id { get; set; }
    
        public virtual mobile_gpsfordepartment mobile_gpsfordepartment { get; set; }
        public virtual mobile_gpslocation mobile_gpslocation { get; set; }
    }
}
