//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OSRFormref
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OSRFormref()
        {
            this.OSRF_items = new HashSet<OSRF_items>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> Fdate { get; set; }
        public string org { get; set; }
        public Nullable<int> Employee_id { get; set; }
        public string prep_by { get; set; }
        public string rev1_by { get; set; }
        public string rev2_by { get; set; }
        public string app1_by { get; set; }
        public string app2_by { get; set; }
        public string del_by { get; set; }
        public Nullable<System.DateTime> del_date { get; set; }
        public string received_by { get; set; }
        public Nullable<System.DateTime> received_date { get; set; }
    
        public virtual master_file master_file { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OSRF_items> OSRF_items { get; set; }
    }
}
