//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OSRF_items
    {
        public int Id { get; set; }
        public string description { get; set; }
        public string quantity { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> OSRFref { get; set; }
    
        public virtual OSRFormref OSRFormref { get; set; }
    }
}
