//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OT_employee_list
    {
        public int Id { get; set; }
        public Nullable<int> OT_link { get; set; }
        public Nullable<int> Employee_id { get; set; }
        public Nullable<System.TimeSpan> OT_from { get; set; }
        public Nullable<System.TimeSpan> OT_to { get; set; }
        public Nullable<int> NO_OTHr { get; set; }
        public string justification { get; set; }
    
        public virtual master_file master_file { get; set; }
        public virtual OVERTIME_APPROVAL OVERTIME_APPROVAL { get; set; }
    }
}
