//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class passport
    {
        public int employee_id { get; set; }
        public int employee_no { get; set; }
        public string company_code { get; set; }
        public string passport_no { get; set; }
        public Nullable<System.DateTime> passport_expiry { get; set; }
        public Nullable<System.DateTime> passport_issue_date { get; set; }
        public Nullable<System.DateTime> passport_return_date { get; set; }
        public string passport_remarks { get; set; }
        public string status { get; set; }
        public string imgpath { get; set; }
        public string changed_by { get; set; }
        public Nullable<System.DateTime> date_changed { get; set; }
    
        public virtual master_file master_file { get; set; }
    }
}
