//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class passport
    {
        public int employee_id { get; set; }
        [Display(Name = "employee id")]
        public int employee_no { get; set; }
        [Display(Name = "company code")]
        public string company_code { get; set; }
        [Display(Name = "passport no")]
        public Nullable<int> passport_no { get; set; }
        [Display(Name = "passport expiry")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:d}")]
        public Nullable<System.DateTime> passport_expiry { get; set; }
        [Display(Name = "passport issue date")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:d}")]
        public Nullable<System.DateTime> passport_issue_date { get; set; }
        [Display(Name = "passport return date")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:d}")]
        public Nullable<System.DateTime> passport_return_date { get; set; }
        [Display(Name = "passport remarks")]
        public string passport_remarks { get; set; }
        public string status { get; set; }
        [Display(Name = "RV expiry")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:d}")]
        public Nullable<System.DateTime> rv_expiry { get; set; }
        [Display(Name = "VL start")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:d}")]
        public Nullable<System.DateTime> vl_start { get; set; }
        [Display(Name = "VL end")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:d}")]
        public Nullable<System.DateTime> vl_end { get; set; }
        [Display(Name = "photo")]
        public string imgpath { get; set; }
        [Display(Name = "changed by")]
        public string changed_by { get; set; }
        [Display(Name = "date changed")]
        public System.DateTime date_changed { get; set; }

        public virtual master_file master_file { get; set; }
    }
}
