//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class payroll_salarystructure
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public payroll_salarystructure()
        {
            this.payroll_salarystructure_deductionformula = new HashSet<payroll_salarystructure_deductionformula>();
            this.payroll_salarystructure_exceptionformula = new HashSet<payroll_salarystructure_exceptionformula>();
            this.payroll_salarystructure_increasementformula = new HashSet<payroll_salarystructure_increasementformula>();
            this.payroll_salarystructure_leaveformula = new HashSet<payroll_salarystructure_leaveformula>();
            this.payroll_salarystructure_overtimeformula = new HashSet<payroll_salarystructure_overtimeformula>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public string create_user { get; set; }
        public Nullable<System.DateTime> change_time { get; set; }
        public string change_user { get; set; }
        public short status { get; set; }
        public double salary_amount { get; set; }
        public System.DateTime effective_date { get; set; }
        public string salary_remark { get; set; }
        public Nullable<int> employee_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<payroll_salarystructure_deductionformula> payroll_salarystructure_deductionformula { get; set; }
        public virtual personnel_employee personnel_employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<payroll_salarystructure_exceptionformula> payroll_salarystructure_exceptionformula { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<payroll_salarystructure_increasementformula> payroll_salarystructure_increasementformula { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<payroll_salarystructure_leaveformula> payroll_salarystructure_leaveformula { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<payroll_salarystructure_overtimeformula> payroll_salarystructure_overtimeformula { get; set; }
    }
}
