//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class payroll_emppayrollprofile
    {
        public int id { get; set; }
        public Nullable<short> payment_mode { get; set; }
        public Nullable<short> payment_type { get; set; }
        public string bank_name { get; set; }
        public string bank_account { get; set; }
        public string personnel_id { get; set; }
        public string agent_id { get; set; }
        public string agent_account { get; set; }
        public int employee_id { get; set; }
    
        public virtual personnel_employee personnel_employee { get; set; }
    }
}
