//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class payroll_reimbursement
    {
        public int id { get; set; }
        public double rmb_amount { get; set; }
        public System.DateTime rmb_time { get; set; }
        public string rmb_file { get; set; }
        public string rmb_remark { get; set; }
        public Nullable<int> employee_id { get; set; }
    
        public virtual personnel_employee personnel_employee { get; set; }
    }
}
