//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class payroll_exceptionformula
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public payroll_exceptionformula()
        {
            this.payroll_salarystructure_exceptionformula = new HashSet<payroll_salarystructure_exceptionformula>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string formula { get; set; }
        public string remark { get; set; }
        public int pay_code_id { get; set; }
    
        public virtual att_paycode att_paycode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<payroll_salarystructure_exceptionformula> payroll_salarystructure_exceptionformula { get; set; }
    }
}
