//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class payroll_payrollpayloadpaycode
    {
        public int id { get; set; }
        public Nullable<double> amount { get; set; }
        public string formula { get; set; }
        public string formula_name { get; set; }
        public int pay_code_id { get; set; }
        public int payload_id { get; set; }
    
        public virtual att_paycode att_paycode { get; set; }
        public virtual payroll_payrollpayload payroll_payrollpayload { get; set; }
    }
}
