//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class payroll_salarystructure_leaveformula
    {
        public int id { get; set; }
        public int salarystructure_id { get; set; }
        public int leaveformula_id { get; set; }
    
        public virtual payroll_leaveformula payroll_leaveformula { get; set; }
        public virtual payroll_salarystructure payroll_salarystructure { get; set; }
    }
}
