//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class payroll_emploan
    {
        public int id { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public string create_user { get; set; }
        public Nullable<System.DateTime> change_time { get; set; }
        public string change_user { get; set; }
        public short status { get; set; }
        public double loan_amount { get; set; }
        public System.DateTime loan_time { get; set; }
        public short refund_cycle { get; set; }
        public double per_cycle_refund { get; set; }
        public Nullable<System.DateTime> loan_clean_time { get; set; }
        public string remark { get; set; }
        public Nullable<int> employee_id { get; set; }
    
        public virtual personnel_employee personnel_employee { get; set; }
    }
}
