//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class payrole
    {
        public int Id { get; set; }
        public int employee_no { get; set; }
        public int con_id { get; set; }
        public string totalpayable { get; set; }
        public string OTRegular { get; set; }
        public string OTFriday { get; set; }
        public string OTNight { get; set; }
        public string HolidayOT { get; set; }
        public string Fot { get; set; }
        public string TotalOT { get; set; }
        public string cashAdvances { get; set; }
        public string HouseAllow { get; set; }
        public string FoodAllow { get; set; }
        public string Timekeeping { get; set; }
        public string Communication { get; set; }
        public string TrafficFines { get; set; }
        public Nullable<int> LWOP { get; set; }
        public string TotalDedution { get; set; }
        public string NetPay { get; set; }
        public string remarks { get; set; }
        public Nullable<int> Absents { get; set; }
        public Nullable<System.DateTime> forthemonth { get; set; }
    
        public virtual contract contract { get; set; }
        public virtual Leave Leave { get; set; }
        public virtual master_file master_file { get; set; }
        public virtual leave_absence leave_absence { get; set; }
    }
}
