//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class payroll_payrollpayload
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public payroll_payrollpayload()
        {
            this.payroll_payrollpayloadpaycode = new HashSet<payroll_payrollpayloadpaycode>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> calc_time { get; set; }
        public Nullable<double> basic_salary { get; set; }
        public Nullable<System.DateTime> effective_date { get; set; }
        public string format_dict { get; set; }
        public Nullable<short> payment_mode { get; set; }
        public Nullable<double> increase { get; set; }
        public Nullable<double> deduction { get; set; }
        public string increase_formula { get; set; }
        public string deduction_formula { get; set; }
        public string increase_formula_name { get; set; }
        public string deduction_formula_name { get; set; }
        public Nullable<double> extra_increase { get; set; }
        public Nullable<double> extra_deduction { get; set; }
        public Nullable<double> total_loan_amount { get; set; }
        public Nullable<double> refund_loan_amount { get; set; }
        public Nullable<double> unrefund_loan_amount { get; set; }
        public Nullable<double> loan_deduction { get; set; }
        public Nullable<double> loan_increase { get; set; }
        public Nullable<double> advance_increase { get; set; }
        public Nullable<double> advance_deduction { get; set; }
        public Nullable<double> reimbursement { get; set; }
        public string total_increase_formula { get; set; }
        public string total_increase_formula_name { get; set; }
        public string total_increase_expression { get; set; }
        public Nullable<double> total_increase { get; set; }
        public string total_deduction_formula { get; set; }
        public string total_deduction_formula_name { get; set; }
        public string total_deduction_expression { get; set; }
        public Nullable<double> total_deduction { get; set; }
        public string total_salary_expression { get; set; }
        public Nullable<double> total_salary { get; set; }
        public int employee_id { get; set; }
    
        public virtual personnel_employee personnel_employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<payroll_payrollpayloadpaycode> payroll_payrollpayloadpaycode { get; set; }
    }
}
