//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class personnel_employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public personnel_employee()
        {
            this.acc_accprivilege = new HashSet<acc_accprivilege>();
            this.att_attemployee = new HashSet<att_attemployee>();
            this.att_attschedule = new HashSet<att_attschedule>();
            this.att_leaveyearbalance = new HashSet<att_leaveyearbalance>();
            this.att_payloadattcode = new HashSet<att_payloadattcode>();
            this.att_payloadbase = new HashSet<att_payloadbase>();
            this.att_payloadeffectpunch = new HashSet<att_payloadeffectpunch>();
            this.att_payloadmulpunchset = new HashSet<att_payloadmulpunchset>();
            this.att_payloadparing = new HashSet<att_payloadparing>();
            this.att_payloadpaycode = new HashSet<att_payloadpaycode>();
            this.att_payloadpunch = new HashSet<att_payloadpunch>();
            this.att_payloadtimecard = new HashSet<att_payloadtimecard>();
            this.att_reporttemplate = new HashSet<att_reporttemplate>();
            this.att_temporaryschedule = new HashSet<att_temporaryschedule>();
            this.att_tempschedule = new HashSet<att_tempschedule>();
            this.ep_eptransaction = new HashSet<ep_eptransaction>();
            this.iclock_biodata = new HashSet<iclock_biodata>();
            this.iclock_biophoto = new HashSet<iclock_biophoto>();
            this.iclock_privatemessage = new HashSet<iclock_privatemessage>();
            this.iclock_transaction = new HashSet<iclock_transaction>();
            this.meeting_meetingentity_attender = new HashSet<meeting_meetingentity_attender>();
            this.meeting_meetingpayloadbase = new HashSet<meeting_meetingpayloadbase>();
            this.meeting_meetingtransaction = new HashSet<meeting_meetingtransaction>();
            this.mobile_announcement = new HashSet<mobile_announcement>();
            this.mobile_announcement1 = new HashSet<mobile_announcement>();
            this.mobile_appnotification = new HashSet<mobile_appnotification>();
            this.mobile_appnotification1 = new HashSet<mobile_appnotification>();
            this.mobile_gpsforemployee = new HashSet<mobile_gpsforemployee>();
            this.mobile_mobileapirequestlog = new HashSet<mobile_mobileapirequestlog>();
            this.payroll_emploan = new HashSet<payroll_emploan>();
            this.payroll_emppayrollprofile = new HashSet<payroll_emppayrollprofile>();
            this.payroll_extradeduction = new HashSet<payroll_extradeduction>();
            this.payroll_extraincrease = new HashSet<payroll_extraincrease>();
            this.payroll_payrollpayload = new HashSet<payroll_payrollpayload>();
            this.payroll_reimbursement = new HashSet<payroll_reimbursement>();
            this.payroll_salaryadvance = new HashSet<payroll_salaryadvance>();
            this.payroll_salarystructure = new HashSet<payroll_salarystructure>();
            this.personnel_assignareaemployee = new HashSet<personnel_assignareaemployee>();
            this.personnel_department = new HashSet<personnel_department>();
            this.personnel_employee_area = new HashSet<personnel_employee_area>();
            this.personnel_employee_flow_role = new HashSet<personnel_employee_flow_role>();
            this.personnel_employee1 = new HashSet<personnel_employee>();
            this.personnel_employeecalendar = new HashSet<personnel_employeecalendar>();
            this.personnel_employeecertification = new HashSet<personnel_employeecertification>();
            this.personnel_employeeextrainfo = new HashSet<personnel_employeeextrainfo>();
            this.personnel_employeeprofile = new HashSet<personnel_employeeprofile>();
            this.personnel_employment = new HashSet<personnel_employment>();
            this.personnel_resign = new HashSet<personnel_resign>();
            this.staff_stafftoken = new HashSet<staff_stafftoken>();
            this.visitor_visitor = new HashSet<visitor_visitor>();
            this.workflow_nodeinstance = new HashSet<workflow_nodeinstance>();
            this.workflow_workflowengine_employee = new HashSet<workflow_workflowengine_employee>();
            this.workflow_workflowinstance = new HashSet<workflow_workflowinstance>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public string create_user { get; set; }
        public Nullable<System.DateTime> change_time { get; set; }
        public string change_user { get; set; }
        public short status { get; set; }
        public string device_password { get; set; }
        public Nullable<int> dev_privilege { get; set; }
        public string card_no { get; set; }
        public string acc_group { get; set; }
        public string acc_timezone { get; set; }
        public string enroll_sn { get; set; }
        public Nullable<int> verify_mode { get; set; }
        public Nullable<short> app_status { get; set; }
        public Nullable<short> app_role { get; set; }
        public Nullable<System.DateTime> last_login { get; set; }
        public bool is_active { get; set; }
        public string session_key { get; set; }
        public string login_ip { get; set; }
        public string emp_code { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string nickname { get; set; }
        public string passport { get; set; }
        public string driver_license_automobile { get; set; }
        public string driver_license_motorcycle { get; set; }
        public string photo { get; set; }
        public string self_password { get; set; }
        public string gender { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public string address { get; set; }
        public string postcode { get; set; }
        public string office_tel { get; set; }
        public string contact_tel { get; set; }
        public string mobile { get; set; }
        public string national { get; set; }
        public string religion { get; set; }
        public string title { get; set; }
        public string ssn { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
        public Nullable<System.DateTime> hire_date { get; set; }
        public string city { get; set; }
        public Nullable<short> emp_type { get; set; }
        public bool enable_payroll { get; set; }
        public string email { get; set; }
        public Nullable<int> leave_group { get; set; }
        public Nullable<int> department_id { get; set; }
        public Nullable<int> position_id { get; set; }
        public Nullable<long> emp_code_digit { get; set; }
        public Nullable<int> superior_id { get; set; }
        public Nullable<int> company_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<acc_accprivilege> acc_accprivilege { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<att_attemployee> att_attemployee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<att_attschedule> att_attschedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<att_leaveyearbalance> att_leaveyearbalance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<att_payloadattcode> att_payloadattcode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<att_payloadbase> att_payloadbase { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<att_payloadeffectpunch> att_payloadeffectpunch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<att_payloadmulpunchset> att_payloadmulpunchset { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<att_payloadparing> att_payloadparing { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<att_payloadpaycode> att_payloadpaycode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<att_payloadpunch> att_payloadpunch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<att_payloadtimecard> att_payloadtimecard { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<att_reporttemplate> att_reporttemplate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<att_temporaryschedule> att_temporaryschedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<att_tempschedule> att_tempschedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ep_eptransaction> ep_eptransaction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<iclock_biodata> iclock_biodata { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<iclock_biophoto> iclock_biophoto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<iclock_privatemessage> iclock_privatemessage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<iclock_transaction> iclock_transaction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<meeting_meetingentity_attender> meeting_meetingentity_attender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<meeting_meetingpayloadbase> meeting_meetingpayloadbase { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<meeting_meetingtransaction> meeting_meetingtransaction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mobile_announcement> mobile_announcement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mobile_announcement> mobile_announcement1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mobile_appnotification> mobile_appnotification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mobile_appnotification> mobile_appnotification1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mobile_gpsforemployee> mobile_gpsforemployee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mobile_mobileapirequestlog> mobile_mobileapirequestlog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<payroll_emploan> payroll_emploan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<payroll_emppayrollprofile> payroll_emppayrollprofile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<payroll_extradeduction> payroll_extradeduction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<payroll_extraincrease> payroll_extraincrease { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<payroll_payrollpayload> payroll_payrollpayload { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<payroll_reimbursement> payroll_reimbursement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<payroll_salaryadvance> payroll_salaryadvance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<payroll_salarystructure> payroll_salarystructure { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<personnel_assignareaemployee> personnel_assignareaemployee { get; set; }
        public virtual personnel_company personnel_company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<personnel_department> personnel_department { get; set; }
        public virtual personnel_department personnel_department1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<personnel_employee_area> personnel_employee_area { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<personnel_employee_flow_role> personnel_employee_flow_role { get; set; }
        public virtual personnel_position personnel_position { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<personnel_employee> personnel_employee1 { get; set; }
        public virtual personnel_employee personnel_employee2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<personnel_employeecalendar> personnel_employeecalendar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<personnel_employeecertification> personnel_employeecertification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<personnel_employeeextrainfo> personnel_employeeextrainfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<personnel_employeeprofile> personnel_employeeprofile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<personnel_employment> personnel_employment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<personnel_resign> personnel_resign { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<staff_stafftoken> staff_stafftoken { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<visitor_visitor> visitor_visitor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<workflow_nodeinstance> workflow_nodeinstance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<workflow_workflowengine_employee> workflow_workflowengine_employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<workflow_workflowinstance> workflow_workflowinstance { get; set; }
    }
}
