//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class personnel_area
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public personnel_area()
        {
            this.acc_acccombination = new HashSet<acc_acccombination>();
            this.acc_accgroups = new HashSet<acc_accgroups>();
            this.acc_accholiday = new HashSet<acc_accholiday>();
            this.acc_accprivilege = new HashSet<acc_accprivilege>();
            this.acc_acctimezone = new HashSet<acc_acctimezone>();
            this.auth_user_auth_area = new HashSet<auth_user_auth_area>();
            this.iclock_terminal = new HashSet<iclock_terminal>();
            this.personnel_area1 = new HashSet<personnel_area>();
            this.personnel_assignareaemployee = new HashSet<personnel_assignareaemployee>();
            this.personnel_employee_area = new HashSet<personnel_employee_area>();
            this.visitor_visitor_area = new HashSet<visitor_visitor_area>();
        }
    
        public int id { get; set; }
        public string area_code { get; set; }
        public string area_name { get; set; }
        public bool is_default { get; set; }
        public Nullable<int> parent_area_id { get; set; }
        public int device_count { get; set; }
        public int employee_count { get; set; }
        public Nullable<int> company_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<acc_acccombination> acc_acccombination { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<acc_accgroups> acc_accgroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<acc_accholiday> acc_accholiday { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<acc_accprivilege> acc_accprivilege { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<acc_acctimezone> acc_acctimezone { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<auth_user_auth_area> auth_user_auth_area { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<iclock_terminal> iclock_terminal { get; set; }
        public virtual personnel_company personnel_company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<personnel_area> personnel_area1 { get; set; }
        public virtual personnel_area personnel_area2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<personnel_assignareaemployee> personnel_assignareaemployee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<personnel_employee_area> personnel_employee_area { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<visitor_visitor_area> visitor_visitor_area { get; set; }
    }
}
