//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class personnel_employment
    {
        public int id { get; set; }
        public short employment_type { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime end_date { get; set; }
        public Nullable<System.DateTime> active_time { get; set; }
        public Nullable<System.DateTime> inactive_time { get; set; }
        public int employee_id { get; set; }
    
        public virtual personnel_employee personnel_employee { get; set; }
    }
}
