//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class personnel_position
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public personnel_position()
        {
            this.personnel_employee = new HashSet<personnel_employee>();
            this.personnel_position1 = new HashSet<personnel_position>();
            this.workflow_workflowengine = new HashSet<workflow_workflowengine>();
        }
    
        public int id { get; set; }
        public string position_code { get; set; }
        public string position_name { get; set; }
        public bool is_default { get; set; }
        public Nullable<int> parent_position_id { get; set; }
        public Nullable<int> company_id { get; set; }
    
        public virtual personnel_company personnel_company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<personnel_employee> personnel_employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<personnel_position> personnel_position1 { get; set; }
        public virtual personnel_position personnel_position2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<workflow_workflowengine> workflow_workflowengine { get; set; }
    }
}
