//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class personnel_employeecertification
    {
        public int id { get; set; }
        public Nullable<System.DateTime> expire_on { get; set; }
        public bool email_alert { get; set; }
        public Nullable<int> before { get; set; }
        public string certification_code { get; set; }
        public string file_name { get; set; }
        public string file { get; set; }
        public int certification_id { get; set; }
        public int employee_id { get; set; }
    
        public virtual personnel_certification personnel_certification { get; set; }
        public virtual personnel_employee personnel_employee { get; set; }
    }
}
