//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class personnel_employeeprofile
    {
        public int id { get; set; }
        public string column_order { get; set; }
        public string disabled_fields { get; set; }
        public string preferences { get; set; }
        public Nullable<System.DateTime> pwd_update_time { get; set; }
        public int emp_id { get; set; }
    
        public virtual personnel_employee personnel_employee { get; set; }
    }
}
