//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class personnel_employeecustomattribute
    {
        public int id { get; set; }
        public string attr_name { get; set; }
        public short attr_type { get; set; }
        public string attr_value { get; set; }
        public bool is_unique { get; set; }
        public bool enable { get; set; }
    }
}
