//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class personnel_department
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public personnel_department()
        {
            this.att_departmentpolicy = new HashSet<att_departmentpolicy>();
            this.att_departmentschedule = new HashSet<att_departmentschedule>();
            this.att_deptattrule = new HashSet<att_deptattrule>();
            this.att_holiday = new HashSet<att_holiday>();
            this.auth_user_auth_dept = new HashSet<auth_user_auth_dept>();
            this.base_linenotifysetting = new HashSet<base_linenotifysetting>();
            this.mobile_gpsfordepartment = new HashSet<mobile_gpsfordepartment>();
            this.personnel_department1 = new HashSet<personnel_department>();
            this.personnel_employee1 = new HashSet<personnel_employee>();
            this.visitor_reservation = new HashSet<visitor_reservation>();
            this.visitor_visitor = new HashSet<visitor_visitor>();
            this.workflow_workflowengine = new HashSet<workflow_workflowengine>();
        }
    
        public int id { get; set; }
        public string dept_code { get; set; }
        public string dept_name { get; set; }
        public bool is_default { get; set; }
        public Nullable<int> parent_dept_id { get; set; }
        public Nullable<int> dept_manager_id { get; set; }
        public Nullable<int> company_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<att_departmentpolicy> att_departmentpolicy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<att_departmentschedule> att_departmentschedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<att_deptattrule> att_deptattrule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<att_holiday> att_holiday { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<auth_user_auth_dept> auth_user_auth_dept { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<base_linenotifysetting> base_linenotifysetting { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mobile_gpsfordepartment> mobile_gpsfordepartment { get; set; }
        public virtual personnel_company personnel_company { get; set; }
        public virtual personnel_employee personnel_employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<personnel_department> personnel_department1 { get; set; }
        public virtual personnel_department personnel_department2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<personnel_employee> personnel_employee1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<visitor_reservation> visitor_reservation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<visitor_visitor> visitor_visitor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<workflow_workflowengine> workflow_workflowengine { get; set; }
    }
}
