//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rec_req_form
    {
        public int Id { get; set; }
        public string projobtitle { get; set; }
        public string department { get; set; }
        public string reporting_to { get; set; }
        public string type_of_hire { get; set; }
        public bool new_hire { get; set; }
        public string justification_NH { get; set; }
        public Nullable<long> proposed_salary { get; set; }
        public string replacement_name { get; set; }
        public Nullable<long> gross_salary { get; set; }
        public string J_P_specification { get; set; }
        public string age_range_from { get; set; }
        public string edu_qua_and_ex_required { get; set; }
        public string add_req_job_resp { get; set; }
    }
}
