//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rest_framework_tracking_apirequestlog
    {
        public int id { get; set; }
        public System.DateTime requested_at { get; set; }
        public int response_ms { get; set; }
        public string path { get; set; }
        public string remote_addr { get; set; }
        public string host { get; set; }
        public string method { get; set; }
        public string query_params { get; set; }
        public string data { get; set; }
        public string response { get; set; }
        public Nullable<int> status_code { get; set; }
        public Nullable<int> user_id { get; set; }
        public string view { get; set; }
        public string view_method { get; set; }
        public string errors { get; set; }
        public string username_persistent { get; set; }
    
        public virtual auth_user auth_user { get; set; }
    }
}
