//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sync_employee
    {
        public int id { get; set; }
        public Nullable<System.DateTime> post_time { get; set; }
        public short flag { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
        public string sync_ret { get; set; }
        public string emp_code { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string dept_code { get; set; }
        public string dept_name { get; set; }
        public string job_code { get; set; }
        public string job_name { get; set; }
        public string area_code { get; set; }
        public string area_name { get; set; }
        public string card_no { get; set; }
        public bool multi_area { get; set; }
        public Nullable<System.DateTime> hire_date { get; set; }
        public string gender { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public string email { get; set; }
        public bool active_status { get; set; }
    }
}
