//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LogisticsSoftEntities : DbContext
    {
        public LogisticsSoftEntities()
            : base("name=LogisticsSoftEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Attendance> Attendances { get; set; }
        public virtual DbSet<MainTimeSheet> MainTimeSheets { get; set; }
        public virtual DbSet<LabourMaster> LabourMasters { get; set; }
        public virtual DbSet<ManPowerSupplier> ManPowerSuppliers { get; set; }
        public virtual DbSet<ProjectList> ProjectLists { get; set; }
    }
}
