//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Training_Effectiveness
    {
        public int Id { get; set; }
        public Nullable<int> Employee_id { get; set; }
        public string traning_prog { get; set; }
        public string traning_date { get; set; }
        public string line_manager { get; set; }
        public string prog_objective { get; set; }
        public string emp_work_per { get; set; }
        public string emp_work_att { get; set; }
        public string emp_work_team { get; set; }
        public Nullable<bool> RC_otheremp { get; set; }
        public Nullable<bool> RC_FDporg { get; set; }
        public string comments { get; set; }
    
        public virtual master_file master_file { get; set; }
    }
}
