//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Training_Request
    {
        public int Id { get; set; }
        public Nullable<int> Employee_id { get; set; }
        public Nullable<System.DateTime> TR_date { get; set; }
        public string line_manager { get; set; }
        public string e_mail_address { get; set; }
        public Nullable<long> contact__no { get; set; }
        public string course_name { get; set; }
        public string training_provider { get; set; }
        public string location { get; set; }
        public string program_type { get; set; }
        public Nullable<System.DateTime> duration_from { get; set; }
        public Nullable<System.DateTime> duration_to { get; set; }
        public string C_S_description { get; set; }
        public string TR_objactive { get; set; }
        public string TR_competencies { get; set; }
        public string comments { get; set; }
        public string budget { get; set; }
        public string TE_program_cost_desc { get; set; }
        public Nullable<long> TE_program_cost_price { get; set; }
        public string TE_transportation_desc { get; set; }
        public string TE_transportation_price { get; set; }
        public string TE_accom_desc { get; set; }
        public Nullable<long> TE_accom_price { get; set; }
        public string TE_diem_desc { get; set; }
        public Nullable<long> TE_diem_price { get; set; }
        public string TE_total_desc { get; set; }
        public Nullable<long> TE_total_price { get; set; }
        public string HR_comments { get; set; }
    
        public virtual master_file master_file { get; set; }
    }
}
