//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class transferlist
    {
        public int Id { get; set; }
        public int Employee_id { get; set; }
        public int cpro_id { get; set; }
        public int npro_id { get; set; }
        public string requested_by { get; set; }
        public string approved_by { get; set; }
        public string effectivedate { get; set; }
        public Nullable<System.DateTime> dateadded { get; set; }
        public Nullable<System.DateTime> datemodifief { get; set; }
        public string reason { get; set; }
    
        public virtual HRprojectlist HRprojectlist { get; set; }
        public virtual HRprojectlist HRprojectlist1 { get; set; }
        public virtual master_file master_file { get; set; }
    }
}
