//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class username
    {
        [Display(Name = "full name")]
        public string full_name { get; set; }
        [Display(Name = "user name")]
        public string aspnet_uid { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
