//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class visa
    {
        public int employee_id { get; set; }
        public Nullable<long> uid_no { get; set; }
        public Nullable<long> file_no { get; set; }
        public int emp_no { get; set; }
        public string place_of_issue { get; set; }
        public string accompanied_by { get; set; }
        public Nullable<System.DateTime> rv_expiry { get; set; }
        public Nullable<System.DateTime> rv_issue { get; set; }
        public string proff_as_per_visa { get; set; }
        public string imgpath { get; set; }
        public string sponsor { get; set; }
        public string changed_by { get; set; }
        public Nullable<System.DateTime> date_changed { get; set; }
    
        public virtual master_file master_file { get; set; }
    }
}
