//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class visitor_visitorbiophoto
    {
        public int id { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public string create_user { get; set; }
        public Nullable<System.DateTime> change_time { get; set; }
        public string change_user { get; set; }
        public short status { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string email { get; set; }
        public string enroll_sn { get; set; }
        public string register_photo { get; set; }
        public System.DateTime register_time { get; set; }
        public string approval_photo { get; set; }
        public short approval_state { get; set; }
        public Nullable<System.DateTime> approval_time { get; set; }
        public string remark { get; set; }
        public int visitor_id { get; set; }
    
        public virtual visitor_visitor visitor_visitor { get; set; }
    }
}
