//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class visitor_visitorconfig
    {
        public int id { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public string create_user { get; set; }
        public Nullable<System.DateTime> change_time { get; set; }
        public string change_user { get; set; }
        public short status { get; set; }
        public short qr_code_policy { get; set; }
        public string code_prefix { get; set; }
        public int code_width { get; set; }
        public int code_start { get; set; }
        public string access_limited { get; set; }
        public short auto_delete_data { get; set; }
        public int data_retention { get; set; }
    }
}
