//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class visitor_visitor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public visitor_visitor()
        {
            this.visitor_visitor_acc_groups = new HashSet<visitor_visitor_acc_groups>();
            this.visitor_visitor_area = new HashSet<visitor_visitor_area>();
            this.visitor_visitorbiodata = new HashSet<visitor_visitorbiodata>();
            this.visitor_visitorbiophoto = new HashSet<visitor_visitorbiophoto>();
            this.visitor_visitorlog = new HashSet<visitor_visitorlog>();
            this.visitor_visitortransaction = new HashSet<visitor_visitortransaction>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public string create_user { get; set; }
        public Nullable<System.DateTime> change_time { get; set; }
        public string change_user { get; set; }
        public short status { get; set; }
        public string visitor_code { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string cert_no { get; set; }
        public string photo { get; set; }
        public string password { get; set; }
        public string card_no { get; set; }
        public string gender { get; set; }
        public string company { get; set; }
        public string ssn { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
        public string email { get; set; }
        public string mobile { get; set; }
        public int visit_quantity { get; set; }
        public string entry_carrying_goods { get; set; }
        public System.DateTime start_time { get; set; }
        public System.DateTime end_time { get; set; }
        public Nullable<System.DateTime> exit_time { get; set; }
        public string exit_carrying_goods { get; set; }
        public string remark { get; set; }
        public int cert_type_id { get; set; }
        public Nullable<int> visit_department_id { get; set; }
        public Nullable<int> visit_reason_id { get; set; }
        public int visited_id { get; set; }
    
        public virtual personnel_certification personnel_certification { get; set; }
        public virtual personnel_department personnel_department { get; set; }
        public virtual personnel_employee personnel_employee { get; set; }
        public virtual visitor_reason visitor_reason { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<visitor_visitor_acc_groups> visitor_visitor_acc_groups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<visitor_visitor_area> visitor_visitor_area { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<visitor_visitorbiodata> visitor_visitorbiodata { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<visitor_visitorbiophoto> visitor_visitorbiophoto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<visitor_visitorlog> visitor_visitorlog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<visitor_visitortransaction> visitor_visitortransaction { get; set; }
    }
}
