//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class visitor_visitortransaction
    {
        public int id { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public string create_user { get; set; }
        public Nullable<System.DateTime> change_time { get; set; }
        public string change_user { get; set; }
        public short status { get; set; }
        public string visitor_code { get; set; }
        public string area { get; set; }
        public Nullable<System.DateTime> punch_time { get; set; }
        public string punch_state { get; set; }
        public int verify_type { get; set; }
        public decimal temperature { get; set; }
        public int is_mask { get; set; }
        public System.DateTime upload_time { get; set; }
        public short source { get; set; }
        public string terminal_sn { get; set; }
        public string terminal_alias { get; set; }
        public Nullable<int> terminal_id { get; set; }
        public Nullable<int> visitor_id { get; set; }
    
        public virtual iclock_terminal iclock_terminal { get; set; }
        public virtual visitor_visitor visitor_visitor { get; set; }
    }
}
