//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class workflow_nodeinstance
    {
        public int id { get; set; }
        public string node_name { get; set; }
        public int order_id { get; set; }
        public short approval_status { get; set; }
        public Nullable<System.DateTime> approval_time { get; set; }
        public string approval_remark { get; set; }
        public bool active { get; set; }
        public bool targeted { get; set; }
        public Nullable<int> approver_employee_id { get; set; }
        public Nullable<int> workflow_instance_id { get; set; }
        public Nullable<int> workflow_node_id { get; set; }
    
        public virtual personnel_employee personnel_employee { get; set; }
        public virtual workflow_workflowinstance workflow_workflowinstance { get; set; }
        public virtual workflow_workflownode workflow_workflownode { get; set; }
    }
}
