//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class workflow_workflownode_notifier
    {
        public int id { get; set; }
        public int workflownode_id { get; set; }
        public int workflowrole_id { get; set; }
    
        public virtual workflow_workflownode workflow_workflownode { get; set; }
        public virtual workflow_workflowrole workflow_workflowrole { get; set; }
    }
}
