//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class workflow_workflownode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public workflow_workflownode()
        {
            this.workflow_nodeinstance = new HashSet<workflow_nodeinstance>();
            this.workflow_workflownode_approver = new HashSet<workflow_workflownode_approver>();
            this.workflow_workflownode_notifier = new HashSet<workflow_workflownode_notifier>();
        }
    
        public int id { get; set; }
        public string node_name { get; set; }
        public int order_id { get; set; }
        public bool approver_by_overall { get; set; }
        public bool notify_by_overall { get; set; }
        public Nullable<int> workflow_engine_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<workflow_nodeinstance> workflow_nodeinstance { get; set; }
        public virtual workflow_workflowengine workflow_workflowengine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<workflow_workflownode_approver> workflow_workflownode_approver { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<workflow_workflownode_notifier> workflow_workflownode_notifier { get; set; }
    }
}
