//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRworks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class workflow_workflowinstance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public workflow_workflowinstance()
        {
            this.workflow_nodeinstance = new HashSet<workflow_nodeinstance>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> approval_time { get; set; }
        public short approval_status { get; set; }
        public string approval_remark { get; set; }
        public string approver { get; set; }
        public string approver_instance { get; set; }
        public int employee_id { get; set; }
        public Nullable<int> workflow_engine_id { get; set; }
    
        public virtual att_changeschedule att_changeschedule { get; set; }
        public virtual att_leave att_leave { get; set; }
        public virtual att_manuallog att_manuallog { get; set; }
        public virtual att_overtime att_overtime { get; set; }
        public virtual att_training att_training { get; set; }
        public virtual att_webpunch att_webpunch { get; set; }
        public virtual meeting_meetingentity meeting_meetingentity { get; set; }
        public virtual meeting_meetingmanuallog meeting_meetingmanuallog { get; set; }
        public virtual personnel_employee personnel_employee { get; set; }
        public virtual visitor_reservation visitor_reservation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<workflow_nodeinstance> workflow_nodeinstance { get; set; }
        public virtual workflow_workflowengine workflow_workflowengine { get; set; }
    }
}
